### ISSUE TITLE
"Unauthorized: Account  doesn't have tunnel" error

### ISSUE THREAD

**Issue by Spunkie** [cloudflare/cloudflared#374] opened 2021-05-19 10:38 UTC
Inspired by https://blog.cloudflare.com/automating-cloudflare-tunnel-with-terraform/ I'm trying to create an init.d bash script that will create/configure/enable a cloudflare tunnel via `cloudflared` and the cloudflare v4 API.

The end goal being to control a named tunnel and it's ingress rules via `docker-compose.yml` ENV vars and without any need for CLI interaction like `cloudflared login`.

The script has a couple of steps, it...
1. create a new named tunnel or fetches info on an existing named tunnel via API
2. saves the API result as a json credentials file in `/etc/cloudflared/`
3. generates a `config.yml` by merging `tunnel`/`credentials-file` based off the API with ingress rules fed in by ENV var. 
4. `cloudflared --no-autoupdate service install`
5. `cloudflared --no-autoupdate tunnel ingress validate`=OK
6. `cloudflared --no-autoupdate tunnel run

On step 6, `cloudflared` seems to picks up the generated config/credential files in `/etc/cloudflared/` just fine. But once it actually tries to create the tunnel connection it fails, spitting out `Unauthorized: Account  doesn't have tunnel` errors. 

I'm using a token with the `Account.Argo Tunnel:Edit` permission and that API lets me interact with tunnel just fine. I thought maybe it's because I had not explicitly enabled argo through the CF dash or have a payment method on the account. So I went and set that up but it didn't change anything, same error. 

So... I'm stuck and not really sure what to do with this error. What am I doing wrong?

This gist has a log of the script running with a real config, as well as the script itself.
https://gist.github.com/Spunkie/966e2ffac829ba470321d120d4471335
If you want to run it yourself just fill in the `CF_API_TOKEN` and `CF_ACCOUNT_ID` at the top of the script, it only supports alpine or ubuntu distros though.

____
The script in the above gist has been trimmed down to be more in scope for this GH issue and expects `cloudflared` to already be installed to function. But it's actually part of a larger repo that builds `cloudflared` from source for multiple archs and then injects `cloudflared` and the init script into [LSIO ](https://www.linuxserver.io/) docker images.

For some context please check out the readme in https://github.com/Spunkie/docker-mods/tree/universal-cloudflared

**Comment by nmldiegues** [comment] 2021-05-19 11:21
> Unauthorized: Account doesn't have tunnel

This error means that your `run` command is trying to connect with a tunnel name/ID that was never `tunnel create`-d.

If you do `cloudflared tunnel list` or `cloudflared tunnel info <name/ID>` you can double check that manually.

**Comment by Spunkie** [comment] 2021-05-19 11:58
> This error means that your run command is trying to connect with a tunnel name/ID that was never tunnel create-d.
> 
> If you do cloudflared tunnel list or cloudflared tunnel info <name/ID> you can double check that manually.

Thanks for the quick reply @nmldiegues 

I was under the impression that the calls I was making to the API replaced the need for `cloudflared tunnel create <NAME>`?

And yes manually confirming, I can't even run `cloudflared tunnel list` or `cloudflared tunnel info <name/ID>` because it complains about the lack of a `cert.pem`. Which doesn't exist because `cloudflared login` never gets run, yes?

**Comment by nmldiegues** [comment] 2021-05-19 12:06
> I was under the impression that the calls I was making to the API replaced the need for cloudflared tunnel create <NAME>?

Based on your description on the issue, the answer is yes.
However, my point is that something is not working as intended in your automation, and I was suggestion a manual step to try to "debug" the situation.

**Comment by Spunkie** [comment] 2021-05-19 12:46
> something is not working as intended in your automation

Ya normally I would a suspect, since my bash skills are not  💯 and I've already shaken out some bugs. But I've been triple checking and unless I'm not understanding the requirements the image state right before `tunnel run` seems correct.

Those requirements being:
1. A working bin at `/usr/local/bin/cloudflared`
2. a tunnel/credentials-file json file `/etc/cloudflared/c879c08b-<REDACTED>-1beb34e6c69a.json`
```json
{"id":"c879c08b-<REDACTED>-1beb34e6c69a","created_at":"2021-05-19T05:37:05.220314Z","deleted_at":null,"name":"newtester5","connections":[],"credentials_file":{"AccountTag":"<REDACTED>","TunnelID":"c879c08b-<REDACTED>-1beb34e6c69a","TunnelName":"newtester5","TunnelSecret":"dGVzdGVydGVzdGVydGVzdGVydGVzdGVydGVzdGVydGVzdGVydGVzdGVydGVzdGVydGVzdGVyCg=="}}
```
3. `/etc/cloudflared/config.yml` validated OK by `tunnel ingress validate`
```yml
tunnel: c879c08b-<REDACTED>-1beb34e6c69a
credentials-file: /etc/cloudflared/c879c08b-<REDACTED>-1beb34e6c69a.json

ingress:
  - hostname: tester-http.<REDACTED>.express
    service: http://localhost:80
  - hostname: tester.valheim.express
    service: hello_world
  - service: http_status:404
```

**Comment by adamchalmers** [comment] 2021-05-20 14:23
You pasted this JSON:
```json
{
  "id": "c879c08b-<REDACTED>-1beb34e6c69a",
  "created_at": "2021-05-19T05:37:05.220314Z",
  "deleted_at": null,
  "name": "newtester5",
  "connections": [],
  "credentials_file": {
    "AccountTag": "<REDACTED>",
    "TunnelID": "c879c08b-<REDACTED>-1beb34e6c69a",
    "TunnelName": "newtester5",
    "TunnelSecret": "dGVzdGVydGVzdGVydGVzdGVydGVzdGVydGVzdGVydGVzdGVydGVzdGVydGVzdGVydGVzdGVyCg=="
  }
}
```

This is the response from the Create Tunnel API. Just checking that's not the contents of the credentials file, is it? The response contains the body of the credentials file that you should create (under the key `credentials_file`.

**Comment by TownLake** [comment] 2021-07-16 11:18
Closing after a few weeks from the last Cloudflare team response; let us know if you need to reopen.

**Closed by TownLake** 2021-07-16 11:18 UTC
Labels: awaiting reply

**Comment by mobycloud** [comment] 2022-02-17 05:52
I tried to use terraform as mentioned in https://blog.cloudflare.com/automating-cloudflare-tunnel-with-terraform/ but without Google Cloud instance - only locally using construction:
```
resource "null_resource" "tunell_install" {
  triggers = {
    always_run = timestamp()
  }
  provisioner "local-exec" {
    command = "/home/uzer/script/tunnel.sh"
  }
}

```
but after running 
```
$ terraform apply -auto-approve
```
successfully created /etc/cloudflared/cert.json with content:
```
{
    "AccountTag"   : "${account}",
    "TunnelID"     : "${tunnel_id}",
    "TunnelName"   : "${tunnel_name}",
    "TunnelSecret" : "${secret}"
}
```
but as I undestood here must be values instead variables? It's seems that metadata_startup_script from instance.tf only applied to Google instance.  How it's possible to change it for using terraform with install CF tunnel locally and running tunnel? Maybe also need to use templatefile but in other .tf file? The curent code block metadata_startup_script:
```
  // This is where we configure the server (aka instance). Variables like web_zone take a terraform variable and provide it to the server so that it can use them as a local variable
  metadata_startup_script = templatefile("./server.tpl",
    {
      web_zone    = var.cloudflare_zone,
      account     = var.cloudflare_account_id,
      tunnel_id   = cloudflare_argo_tunnel.auto_tunnel.id,
      tunnel_name = cloudflare_argo_tunnel.auto_tunnel.name,
      secret      = random_id.tunnel_secret.b64_std
    })

```
