### ISSUE TITLE
MacOS launchd config is missing `tunnel run` arguments

### ISSUE THREAD

**Issue by daxhuiberts** [cloudflare/cloudflared#589] opened 2022-03-02 16:16 UTC
**Describe the bug**
When installing cloudflared as a system service using `sudo cloudflared service install` it installs a service file, but upon starting it, it doesn't run.

**To Reproduce**
1. Have a working config file in `/etc/cloudflared/config.yml`
2. Install the service file with `sudo cloudflared service install`
3. Start the service with `sudo launchctl start com.cloudflare.cloudflared`
4. Check tunnels with `cloudflared tunnel list`
5. See that the tunnel with the config in `/etc/cloudflared/config.yml` doesn't have any connections.
6. Check the error log in `/Library/Logs/com.cloudflare.cloudflared.err.log`
7. See that the file is filled with the line `Use `cloudflared tunnel run` to start tunnel <tunnel_id>`

**Expected behavior**
The service install on MacOS should install a correct service file which should run the daemon succesfully.

**Environment and versions**
 - OS: MacOS
 - Architecture: ARM
 - Version: 2022.2.2

**Logs and errors**
Use `cloudflared tunnel run` to start tunnel <tunnel_id>
Use `cloudflared tunnel run` to start tunnel <tunnel_id>
Use `cloudflared tunnel run` to start tunnel <tunnel_id>
Use `cloudflared tunnel run` to start tunnel <tunnel_id>
Use `cloudflared tunnel run` to start tunnel <tunnel_id>
...

**Additional context**
The issue is located here: https://github.com/cloudflare/cloudflared/blob/master/cmd/cloudflared/macos_service.go#L52
I've added
```
<string>tunnel</string>
<string>run</string>
```
following that line, reloaded the config file and restarted the service and then it is running succesfully.

**Comment by nmldiegues** [comment] 2022-03-02 16:46
Thanks for the detailed report. I think this is a duplicate of https://github.com/cloudflare/cloudflared/issues/327

The good news is that we'll be fixing this soon in scope of a bigger feature.

**Closed by nmldiegues** 2022-03-02 16:46 UTC
Labels: bug, awaiting reply
