### ISSUE TITLE
Unable to Tunnel "--Hostname"  to "Localhost:port" - 502 Error 

### ISSUE THREAD

**Issue by stevenanthonyrevo** [cloudflare/cloudflared#270] opened 2020-12-02 21:31 UTC
I am receiving a 502 error when tunneling from hostname (https://subdomain.domain.com) to a random local port (http://localhost:3500).

Here is my command after the initial setup and login. 

```
sudo cloudflared tunnel --hostname test.exampledomain.com http://localhost:3400
 ```
I am receiving a 502 error on the live page and a proxy error from the tunnel outputs. I've listed below. 
 
```
CF-RAY: MIA Proxying to ingress 0 error: Error proxying request to origin: dial tcp [::1]:8080: connect: connection refused
```

**Comment by nmldiegues** [comment] 2020-12-02 22:18
Hello @stevenanthonyrevo .

I think you are missing the flag `--url` before your `http://localhost:3400` argument.

See https://developers.cloudflare.com/argo-tunnel/run-tunnel for the corresponding example with a pre-created named tunnel (which is the recommended way for running tunnels, see https://blog.cloudflare.com/argo-tunnels-that-live-forever/ for insights about it).

**Comment by stevenanthonyrevo** [comment] 2020-12-03 00:26
Hey @nmldiegues 

Just tried adding the `--url` and it worked, thank you!  👍  

I may have been looking at this command mentioned on the live docs wrong this entire time and had forgotten the `--url` flag.  
```
cloudflared tunnel --hostname example.com http://localhost:8080
``` 
 [https://github.com/cloudflare/cloudflare-docs/blob/3ceab09a927da02aab03c53ff54852795a3c69df/products/argo-tunnel/src/content/reference/common-errors.md](https://github.com/cloudflare/cloudflare-docs/blob/3ceab09a927da02aab03c53ff54852795a3c69df/products/argo-tunnel/src/content/reference/common-errors.md) 

Let me know if this confused anyone else. Just curious, does the Argo Tunnel always have to be a blocking process in the terminal, or can it be pushed into a quiet background PID?

**Comment by nmldiegues** [comment] 2020-12-03 10:06
> I may have been looking at this command mentioned on the live docs wrong this entire time and had forgotten the `--url` flag.
> 
> ```
> cloudflared tunnel --hostname example.com http://localhost:8080
> ```
> 
> https://github.com/cloudflare/cloudflare-docs/blob/3ceab09a927da02aab03c53ff54852795a3c69df/products/argo-tunnel/src/content/reference/common-errors.md

I am afraid you were looking at some "dead docs". I.e. those are not referred to by any live documentation at https://developers.cloudflare.com/argo-tunnel/


> Just curious, does the Argo Tunnel always have to be a blocking process in the terminal, or can it be pushed into a quiet background PID?

Nothing prevents you from making it a background process.

In practice, long standing users normally set it up as a service. See https://developers.cloudflare.com/argo-tunnel/run-tunnel/run-as-service

**Comment by nmldiegues** [comment] 2020-12-03 10:07
Glad that the issue is addressed. I'll be closing this up, but feel free to follow up with any additional questions.

**Closed by nmldiegues** 2020-12-03 10:07 UTC

**Comment by PeerUthman** [comment] 2022-08-01 16:32
Whenever I try to open the link from ngrok it shows warning, and after refreshing the page it gives access to that website..........how to skip that warning page?

**Comment by abelinkinbio** [comment] 2022-08-01 17:49
👋 @PeerUthman As a heads up, this is the Cloudflare Tunnel GitHub repository. It sounds like you're looking for the [ngrok repository](https://github.com/inconshreveable/ngrok/issues). However, if you'd like to give Cloudflare Tunnel a try instead you can get started for free by following our [quickstart guide](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/#set-up-a-tunnel-remotely-dashboard-setup). It should have you up and running in just a few minutes. Let us know what you think and hope your issue gets resolved in the meantime!
