### ISSUE TITLE
Argo Tunnel - Missing headers when passing an invalid path.

### ISSUE THREAD

**Issue by Wrhector** [cloudflare/cloudflared#81] opened 2019-04-02 00:52 UTC
We've noticed an odd scenario where when we pass in an invalid path, for example:
```
//test/
```

The request would go through to the root `/` but without any of the client headers, user agent, ip etc. Giving something like this in our nginx logs:
```
127.0.0.1 - - servername [01/Apr/2019:12:48:01 -0700] "GET / HTTP/1.1" 200 28392 "-" "Go-http-client/1.1" "-"
```

The issue seems to be than when the headers are copied over in this function:
https://github.com/cloudflare/cloudflared/blob/8c6cfa34aa62e77fbc6d0a35544d8d0f04198f31/origin/tunnel.go#L582

When a bad path is found, it will exit the function without finishing copying the headers, but the request will still continue:
https://github.com/cloudflare/cloudflared/blob/8c6cfa34aa62e77fbc6d0a35544d8d0f04198f31/origin/tunnel.go#L464

It seems either it should continue copying the headers, or stop processing the request.

**Comment by sssilver** [comment] 2019-04-02 16:15
Thanks for catching this, and for the well-written ticket @Wrhector! We'll look into this soon.

**Comment by sssilver** [comment] 2019-07-25 16:42
@Wrhector I'm failing to reproduce this with the following unit test:
```go
func TestH2RequestHeadersToH1Request_InvalidHostPath(t *testing.T) {
	request, err := http.NewRequest(http.MethodGet, "http://example.com//test/", nil)
	assert.NoError(t, err)

	headersConversionErr := H2RequestHeadersToH1Request(
		[]h2mux.Header{
			h2mux.Header{
				Name:  "Mock header 1",
				Value: "Mock value 1",
			},
			h2mux.Header{
				Name:  "Mock header 2",
				Value: "Mock value 2",
			},
		},
		request,
	)

	assert.Equal(t, http.Header{
		"Mock header 1": []string{"Mock value 1"},
		"Mock header 2": []string{"Mock value 2"},
	}, request.Header)

	assert.NoError(t, headersConversionErr)
}
```

Is this still a problem?

**Comment by rabbitt** [comment] 2019-09-09 16:39
@sssilver Out of curiosity, is there a particular reason urls aren't normalized (i.e., extra slashes stripped) prior to being sent to the origin? That certainly would have prevented OPs issue (related to double slashes, which incidentally, nginx actually normalizes away prior to backend processing itself), and would also remove any security concerns double slashes might present. Side note: it would also have the added benefit of preventing the 502 responses (due to "invalid path" errors) my company has been seeing when clients request, e.g., `//some/page` accidentally.

Seems like something simple such as the following would work (using [path.Clean](https://golang.org/pkg/path/#Clean)), or am I missing something more fundamental here?:
 
change:
https://github.com/cloudflare/cloudflared/blob/a10785a701ca673457da269519806ac2705e2e9e/streamhandler/request.go#L48
to:
```
  # normalize path down to the shortest equivalent
  reqPath := path.Clean(header.Value)
  # XXX: it's unlikely that we'll end up with '.' returned from path.Clean
  if reqPath == "." {
    reqPath = "/"
  }
  u, err := url.Parse(reqPath)
```

**Comment by sssilver** [comment] 2019-09-09 18:11
Hi @rabbitt !

The paradigm we subscribe to is that cloudflared should be as transparent as possible. That means any sort of normalization would be tampering with the request that we'd like to avoid.

This reoccurrence of this issue has been unfortunate, but we have a fix that we're planning to release in a matter of days that should (hopefully) address this for good. I'll post a reference to the commit once it lands here, curious what you think about how we solved it.

**Comment by rabbitt** [comment] 2019-09-09 18:41
Hi @sssilver,

That goal is certainly a worthy and appropriate one given the use case for cloudflared. To be fair though, the code is already making assumptions about the request by failing on requests with double slashes (presumably to protect against escaping the base url, a function which seems more appropriately placed with Cloudflare's WAF offering). 

I'm hopeful that the changes you referenced will instead allow cloudflared to function as a traditional transparent proxy, with no assumptions made about content prior to passing to the origin. :-) 

Thank you for responding - I look forward to seeing the changes!

--
Carl

**Comment by rabbitt** [comment] 2019-09-19 21:36
@sssilver Has that commit landed yet?

**Comment by daltoniam** [comment] 2020-07-15 21:01
This fix landed a while back, sorry about the delayed response. The latest version of cloudflared (`2020.7.3`) should have the fix. Thanks again for the report!

**Closed by daltoniam** 2020-07-15 21:01 UTC
Labels: bug, confirmed
