### ISSUE TITLE
h2mux handshake with edge error

### ISSUE THREAD

**Issue by xUnholy** [cloudflare/cloudflared#203] opened 2020-05-27 08:44 UTC
I'm attempting to use argo tunnel in the sidecar kubernetes approach as explained here: https://developers.cloudflare.com/argo-tunnel/reference/sidecar/ 

https://github.com/cloudflare/cloudflared/blob/fbe2989f61fcdcecc4062b6c10cdabb571a6d6d7/origin/tunnel.go#L600

I'm coming across a strange issue when trying to create the tunnel as shown below:

```
❯ k logs hello-69464c85c9-9ql2j -c tunnel -f
time="2020-05-27T08:34:54Z" level=warning msg="Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /usr/local/etc/cloudflared /etc/cloudflared]"
time="2020-05-27T08:34:54Z" level=warning msg="At debug level, request URL, method, protocol, content legnth and header will be logged. Response status, content length and header will also be logged in debug level."
time="2020-05-27T08:34:54Z" level=info msg="Version 2020.5.1-6-ga908453"
time="2020-05-27T08:34:54Z" level=info msg="GOOS: linux, GOVersion: go1.14.3, GoArch: arm64"
time="2020-05-27T08:34:54Z" level=info msg=Flags hostname=hello.raspbernetes.com loglevel=debug no-autoupdate=true origincert=/etc/cloudflared/cert.pem proxy-dns-upstream="https://1.1.1.1/dns-query, https://1.0.0.1/dns-query" url="http://127.0.0.1:8080"
time="2020-05-27T08:34:55Z" level=debug msg="Reading origin cert from /etc/cloudflared/cert.pem"
time="2020-05-27T08:34:55Z" level=info msg="Starting metrics server" addr="127.0.0.1:46273/metrics"
time="2020-05-27T08:35:16Z" level=info msg="Proxying tunnel requests to http://127.0.0.1:8080"
time="2020-05-27T08:35:18Z" level=debug msg="Giving connection its new address 198.41.200.193:7844" connID=0 function=GetAddr subsystem=edgediscovery
time="2020-05-27T08:35:32Z" level=error msg="Tunnel creation failure" connectionID=0 error="h2mux handshake with edge error: Handshake error: 1000 handshake timeout"
time="2020-05-27T08:35:32Z" level=info msg="Initiating graceful shutdown due to h2mux handshake with edge error: Handshake error: 1000 handshake timeout ..."
time="2020-05-27T08:35:32Z" level=error msg="Quitting due to error" error="h2mux handshake with edge error: Handshake error: 1000 handshake timeout"
time="2020-05-27T08:35:32Z" level=info msg="Metrics server stopped"
h2mux handshake with edge error: Handshake error: 1000 handshake timeout
```

My configuration is a literal copy/paste from the demonstration however, I'll post it in case I'm missing something?

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: raspbernetes/custom-error-pages
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 40Mi
            requests:
              cpu: 20m
              memory: 40Mi
        - name: tunnel
          image: raspbernetes/cloudflared:2020.5.1
          imagePullPolicy: Always
          command: ['cloudflared', 'tunnel']
          args:
            - --url=http://127.0.0.1:8080
            - --hostname=hello.raspbernetes.com
            - --origincert=/etc/cloudflared/cert.pem
            - --no-autoupdate
            - --origin-server-name raspbernetes.com
            - --loglevel=debug
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /etc/cloudflared
              name: tunnel-secret
              readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: tunnel-secret
          secret:
            secretName: raspbernetes.com-cloudflared-cert
```

**Comment by xUnholy** [comment] 2020-05-27 08:45
I've raised an issue in the community and has some support with no success here: https://community.cloudflare.com/t/argo-tunnel-kubernetes-sidecar-model/169342/4

**Comment by xUnholy** [comment] 2020-05-27 09:17
Applied more to the logging

```
        - name: tunnel
          image: raspbernetes/cloudflared:2020.5.1
          imagePullPolicy: IfNotPresent
          command: ['cloudflared', 'tunnel']
          args:
            - --url=http://127.0.0.1:8080
            - --hostname=hello.raspbernetes.com
            - --origincert=/etc/cloudflared/cert.pem
            - --no-autoupdate
            - --origin-server-name=raspbernetes.com
            - --loglevel=debug
            - --proto-loglevel=warn
            - --retries=8
```

Got the following logs:

```
❯ k logs echo-647d594776-ntj86 -c tunnel -f
time="2020-05-27T09:14:09Z" level=warning msg="Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /usr/local/etc/cloudflared /etc/cloudflared]"
time="2020-05-27T09:14:09Z" level=warning msg="At debug level, request URL, method, protocol, content legnth and header will be logged. Response status, content length and header will also be logged in debug level."
time="2020-05-27T09:14:10Z" level=info msg="Version 2020.5.1-6-ga908453"
time="2020-05-27T09:14:10Z" level=info msg="GOOS: linux, GOVersion: go1.14.3, GoArch: arm64"
time="2020-05-27T09:14:10Z" level=info msg=Flags hostname=hello.raspbernetes.com loglevel=debug no-autoupdate=true origin-server-name=raspbernetes.com origincert=/etc/cloudflared/cert.pem proto-loglevel=warn proxy-dns-upstream="https://1.1.1.1/dns-query, https://1.0.0.1/dns-query" retries=8 transport-loglevel=warn url="http://127.0.0.1:8080"
time="2020-05-27T09:14:12Z" level=info msg="Starting metrics server" addr="127.0.0.1:36057/metrics"
time="2020-05-27T09:14:12Z" level=debug msg="Reading origin cert from /etc/cloudflared/cert.pem"
time="2020-05-27T09:14:36Z" level=info msg="Proxying tunnel requests to http://127.0.0.1:8080"
time="2020-05-27T09:14:39Z" level=debug msg="Giving connection its new address 198.41.200.193:7844" connID=0 function=GetAddr subsystem=edgediscovery
time="2020-05-27T09:14:50Z" level=error msg="Tunnel creation failure" connectionID=0 error="h2mux handshake with edge error: read tcp 10.32.0.8:38346->198.41.200.193:7844: read: connection reset by peer"
time="2020-05-27T09:14:50Z" level=info msg="Initiating graceful shutdown due to h2mux handshake with edge error: read tcp 10.32.0.8:38346->198.41.200.193:7844: read: connection reset by peer ..."
time="2020-05-27T09:14:50Z" level=info msg="Metrics server stopped"
time="2020-05-27T09:14:50Z" level=error msg="Quitting due to error" error="h2mux handshake with edge error: read tcp 10.32.0.8:38346->198.41.200.193:7844: read: connection reset by peer"
h2mux handshake with edge error: read tcp 10.32.0.8:38346->198.41.200.193:7844: read: connection reset by peer
```

**Comment by xUnholy** [comment] 2020-05-29 07:15
@acmacalister @sssilver would you know who is the best person to direct this issue too?

**Comment by hortocam** [comment] 2020-07-07 15:57
I am experiencing the same issue.  

I've used public arm64 builds of cloudflared and also built my own several different ways.  They all fail the same way within a sidecar container running on a Raspberry PI 4 (arm64/v8) with Ubuntu 20.04 & microk8s.  

I can run microk8s on my Macbook and using the same deployment it will work fine. 

I can run cloudflared directly on the Macbook and connect successfully. 

I can run cloudflared directly on the above Raspberry PI (build on that device) and it connects successfully.  

Would really like to get some additional insight on how to move this forward.

Thanks.

**Comment by xUnholy** [comment] 2020-07-09 09:35
@hortocam I have not received a lot of support around this issue. I did have a thought that perhaps this is related to network policies potentially, can you confirm you're using network policies?

**Comment by hortocam** [comment] 2020-07-09 16:32
Thanks for responding.  I am running a basic single node microk8s cluster.  I have 5 nodes in total but have only the one I'm trying to get things running on first. 

I am using the standard kubenet.  No network policies.  

For now, I am running the cloudflared as a service from the node directly and forwarding to a hostport in the cluster.  I'll have to label Traefik to run only on this node so it can route traffic from there.  I'm able to get ingress successfully.  

Next objective is to get TLS & Let's Encrypt working for it.

**Comment by passcod** [comment] 2020-10-12 13:26
Running into the same thing here.

Version: 2020.10.0

Invocation:

```
~# cloudflared tunnel \
--url=http://10.20.30.40 \
--hostname=myhostname.example.com \
--origincert=cloudflared.pem \
--metrics=localhost:1234 \
--no-autoupdate \
--loglevel=debug \
--proto-loglevel=warn
```

The erroneous log looks like this:

```
cloudflared
DEBUG[2020-10-12T11:31:23Z] Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
cloudflared
INFO[2020-10-12T11:31:23Z] Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
cloudflared
INFO[2020-10-12T11:31:23Z] Version 2020.10.0
cloudflared
INFO[2020-10-12T11:31:23Z] GOOS: linux, GOVersion: go1.13.3, GoArch: amd64
cloudflared
INFO[2020-10-12T11:31:23Z] Environment variables map[hostname:myhostname.example.com loglevel:debug metrics:localhost:1234 no-autoupdate:true origincert:/etc/cloudflared/cert.pem proto-loglevel:warn proxy-dns-upstream:https://1.1.1.1/dns-query, https://1.0.0.1/dns-query retries:8 transport-loglevel:warn url:http://10.20.30.40]
cloudflared
INFO[2020-10-12T11:31:23Z] Starting metrics server on 127.0.0.1:1234/metrics
cloudflared
DEBUG[2020-10-12T11:31:24Z] Reading origin cert from /etc/cloudflared/cert.pem
cloudflared
INFO[2020-10-12T11:31:54Z] Proxying tunnel requests to http://10.20.30.40
cloudflared
DEBUG[2020-10-12T11:32:00Z] edgediscovery - GetAddr: Giving connection its new address 198.41.200.53:7844: connID: 0
cloudflared
ERROR[2020-10-12T11:32:13Z] Connection 0 failed: h2mux handshake with edge error: Handshake error: 1000 handshake timeout
cloudflared
INFO[2020-10-12T11:32:13Z] Initiating graceful shutdown due to h2mux handshake with edge error: Handshake error: 1000 handshake timeout ...
cloudflared
INFO[2020-10-12T11:32:13Z] Metrics server stopped
cloudflared
ERROR[2020-10-12T11:32:13Z] Quitting due to error: h2mux handshake with edge error: Handshake error: 1000 handshake timeout
cloudflared
h2mux handshake with edge error: Handshake error: 1000 handshake timeout
```

Successes:

- From my workstation (in different LAN)
- From a workstation running in the LAN of the kubernetes cluster
- From any of the kubernetes hosts

Fails:

- When set up as a sidecar
- When set up as a separate kubernetes deployment
- When run inside a manually-created docker container on any of the kubernetes hosts, and on workstations

Interestingly, the "free tunnel" mode (running without an origin cert) works fine in that third failing scenario (manual docker container on k8s hosts), but not from kubernetes itself.

Armed with the reproduceability of running it in docker to get a fail, I started investigating, but didn't get anything very useful. However, I managed to obtain success within a manually-created docker, both on workstations and on the k8s hosts, when I built my own cloudflared image, with this dockerfile:

```dockerfile
FROM alpine AS builder

RUN apk update
RUN apk add git go build-base

RUN git clone https://github.com/cloudflare/cloudflared /build
WORKDIR /build
RUN git checkout 2020.10.0
RUN make cloudflared

FROM alpine
COPY --from=builder /build/cloudflared /usr/bin/cloudflared
ENTRYPOINT ["/usr/bin/cloudflared", "tunnel", "--metrics=0.0.0.0:1234", "--no-autoupdate", "--origincert=/etc/cloudflared/cert.pem"]
```

Still no success within kubernetes, but this is progress! I will keep investigating...

**Comment by passcod** [comment] 2020-10-14 10:24
By accident, while trying to set up a tcpdump alongside the tunnel from inside the container, I found something interesting... so I did further testing, only varying the way cloudflared is called, with the above image (minus the entrypoint), in kubernetes:

| Works? | directly (no bash) | `bash -c ...` | `bash -c exec ...` | `--no-autoupdate` | with tcpdump running alongside |
|:-:|:-:|:-:|:-:|:-:|:-:|
| **Yes** | | ☑️ | | | ☑️ |
| No | | ☑️ | | ☑️ | |
| No | | | ☑️ | ☑️ | |
| No | ☑️ | | | ☑️ | |
| **Yes** | ☑️ | | | | |
| **Yes** | | | ☑️ | | |
| No | | ☑️ | | ☑️ | ☑️ |

I'm pretty mad because the autoupdate doesn't even _work_! It times out on the check:

    ERROR[2020-10-14T09:33:03Z] update check failed: Get https://update.argotunnel.com?arch=amd64&os=linux: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

You'll notice there's rows missing if all the possibilities were to be checked: that's because it's not possible to run directly or with `exec` alongside tcpdump. I think it's pretty conclusive anyway. I have no idea _why_ or _how_... but **not disabling auto updates makes it go**.

I tried this with the official image, too, and it works there as well.

**Comment by xUnholy** [comment] 2020-10-15 07:58
I stopped bothering trying to use Cloudflare Argo tunnel in the cluster as a side-car to my ingress controller, instead, I ended up using DDNS as my problem was I don't have a static IP.

**Comment by TownLake** [comment] 2021-02-23 10:14
Thanks for the reports. We're working to replace `h2mux` with `http2` in `cloudflared`. You can enable this by adding this to your configuration file:

`protocol: http2`

Please let us know if that removes the error you've seen here. Apologies for the delayed response.

**Comment by TownLake** [comment] 2021-03-14 20:53
Closing while awaiting reply; please reopen or let us know if the last suggestion helped solve the issue.

**Closed by TownLake** 2021-03-14 20:53 UTC
Labels: awaiting reply
