### ISSUE TITLE
Add debian bullseye to the offical repository

### ISSUE THREAD

**Issue by fancsali** [cloudflare/cloudflared#676] opened 2022-06-22 10:13 UTC
Looking at https://pkg.cloudflare.com/#debian-title one would learn that the latest version that is supported is `buster`, which is `oldstable` by now.

**Debian 11** (`bullseye`) has been out for a while now, so it'd be nice to have a version in the official repositiories.

Double checking whether it's actually unsupported (adding the repo as per the instructions and trying `apt update`) one can see, it's indeed unsupported:

```
pi@devberrypi:~ $ sudo apt update
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian bullseye InRelease [23.7 kB]                                     
Ign:3 https://pkg.cloudflare.com buster InRelease                          
Get:4 https://pkg.cloudflare.com buster Release [7,644 B]
Get:5 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.2 MB]
Get:6 https://pkg.cloudflare.com buster Release.gpg [516 B]
Get:7 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [279 kB]
Fetched 13.6 MB in 15s (908 kB/s)                                                                                                                                                                        
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
18 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://pkg.cloudflare.com buster InRelease' doesn't support architecture 'armhf'
```

**Comment by nmldiegues** [comment] 2022-06-22 10:58
I think this is a duplicate of https://github.com/cloudflare/cloudflared/issues/576

We'll very soon have a revamped pkg repo available with all modern flavors and architectures supported. We'll keep that issue updated once we make it available

**Closed by nmldiegues** 2022-06-22 10:58 UTC
