### ISSUE TITLE
Cloudflare Tunnel randomly stops serving traffic 

### ISSUE THREAD

**Issue by Albonycal** [cloudflare/cloudflared#698] opened 2022-07-17 09:53 UTC
**Cloudflare tunnel randomly not working**
The daemon is still running but no traffic reaches it.. restarting the daemon fixes it for a while, but then it happens again. 
No pattern observed, just randomly stops working 

**Environment and versions**
 - OS: Ubuntu Server 20.04
 - Architecture: AMD64
 - Version: 2022.7.1
- Running as a systemd service

**Logs and errors**
```
Jul 17 12:08:33 phoenix cloudflared[470354]: 2022-07-17T06:38:33Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:33 phoenix cloudflared[470354]: 2022-07-17T06:38:33Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:34 phoenix cloudflared[470354]: 2022-07-17T06:38:34Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:34 phoenix cloudflared[470354]: 2022-07-17T06:38:34Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:34 phoenix cloudflared[470354]: 2022-07-17T06:38:34Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:34 phoenix cloudflared[470354]: 2022-07-17T06:38:34Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:35 phoenix cloudflared[470354]: 2022-07-17T06:38:35Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:35 phoenix cloudflared[470354]: 2022-07-17T06:38:35Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:36 phoenix cloudflared[470354]: 2022-07-17T06:38:36Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:36 phoenix cloudflared[470354]: 2022-07-17T06:38:36Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:36 phoenix cloudflared[470354]: 2022-07-17T06:38:36Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:36 phoenix cloudflared[470354]: 2022-07-17T06:38:36Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
Jul 17 12:08:36 phoenix cloudflared[470354]: 2022-07-17T06:38:36Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>

```
Its showing this error, but it used to show some TCP connect error for the URL inside LAN

**Additional context**
I am using the `--protocol http2` flag because quic doesn't work 
host: mirror.albony.xyz
cloudflare email: albonycal@gmail.com

**Comment by sudarshan-reddy** [comment] 2022-07-17 10:03
> I am using the --protocol http2 flag because quic doesn't work

Can you explain what you mean by `doesn't work`? We'll need a little more information to help you. :) 

> Incoming request ended abruptly: context canceled

This basically means the requests to your tunnel were cancelled because of a timeout. Is your origin service slow my any chance?

**Comment by Albonycal** [comment] 2022-07-17 10:19
> This basically means the requests to your tunnel were cancelled because of a timeout. Is your origin service slow my any chance?

no? when cloudflared is "down" my origin services works fine, and at gigabit LAN speeds.

**Comment by Albonycal** [comment] 2022-07-17 10:21
> Can you explain what you mean by doesn't work? We'll need a little more information to help you. :)
it fails to connect using quic, I have tried everything, even setting up port triggering for it 
so now I force it to use HTTP2
before cloudflared use to use HTTP2 by default 
idk why it tries to use quic now

**Comment by Albonycal** [comment] 2022-07-17 10:22
> This basically means the requests to your tunnel were cancelled because of a timeout. Is your origin service slow my any chance?

and even if it's slow, cloudflare tunnel shouldn't just crash ?

**Comment by Albonycal** [comment] 2022-07-17 10:22
also, I have two instances of cloudflare now, both do the same thing.

**Comment by sudarshan-reddy** [comment] 2022-07-17 10:29
> it fails to connect using quic, I have tried everything, even setting up port triggering for it
so now I force it to use HTTP2
before cloudflared use to use HTTP2 by default
idk why it tries to use quic now

What is your system running on? Do you have UDP egress enabled? quic is the direction we want to take the future of cloudflared for, for both performance and stability reasons.

**Comment by sudarshan-reddy** [comment] 2022-07-17 10:30
> and even if it's slow, cloudflare tunnel shouldn't just crash ?

Can you share crash logs? I only see 

```
Jul 17 12:08:36 phoenix cloudflared[470354]: 2022-07-17T06:38:36Z ERR  error="Incoming request ended abruptly: context canceled" cfRay=>
```

**Comment by Albonycal** [comment] 2022-07-17 10:33
uh by "crash" it doesn't really crash, the daemon is still running but it doesn't serve traffic

**Comment by Albonycal** [comment] 2022-07-17 11:33
also, is this normal behaviour? 
![image](https://user-images.githubusercontent.com/67057319/179396123-6ec89809-6ddb-4a63-ab53-f12d0e83da1f.png)
notice the space between the bars, it drops the speed when I am downloading something and then regains it

**Comment by sudarshan-reddy** [comment] 2022-07-20 10:24
That is expected behaviour since your bandwidth is shared.

**Comment by sudarshan-reddy** [comment] 2022-07-20 10:25
> it fails to connect using quic, I have tried everything, even setting up port triggering for it

Did you enable UDP egress in your firewall?

**Comment by Albonycal** [comment] 2022-07-20 10:29
yea I did

**Comment by Albonycal** [comment] 2022-07-20 11:05
I added this to my router config 
![image](https://user-images.githubusercontent.com/67057319/179967294-fac6f5a3-326e-44d9-8508-cdd9e14ba000.png)

**Comment by sudarshan-reddy** [comment] 2022-07-24 04:38
Nice! Are you still having these issues?

**Comment by Albonycal** [comment] 2022-07-24 10:46
hmm no.. but these are still there 
![image](https://user-images.githubusercontent.com/67057319/180643623-8773cf34-4d03-4f52-a7ba-25a83edd1254.png)
and I am see some quic errors

**Comment by Albonycal** [comment] 2022-07-25 10:16
still getting a lot of "incoming request ended abruptly"

**Comment by sudarshan-reddy** [comment] 2022-07-27 08:20
This is indicative of your clients closing these requests. What is the experience you get on the eyeball side?

**Comment by Albonycal** [comment] 2022-07-27 09:52
what do you mean by the "eyeball" side?

**Comment by Albonycal** [comment] 2022-07-27 09:57
That particular service is being monitored here, https://archlinux.org/mirrors/albony.xyz/
and I see some errors which shouldn't be there.. 
![image](https://user-images.githubusercontent.com/67057319/181219630-5004b3b8-09f4-43af-8f99-8d7399b4a80a.png)

**Comment by Albonycal** [comment] 2022-08-01 11:03
i rechecked and confirmed that the same issue is happening.. and restarting the daemon "fixes" it temperorrily,,, but it happens again

**Comment by Albonycal** [comment] 2022-08-01 17:46
I wonder if a burst of high traffic can trigger a bug in cloudflared or something that makes it unresponsive.. 
This machine is quite old so maybe that's the issue? but still it shouldn't act like this, looks like a cloudflared bug to me ?

**Comment by sudarshan-reddy** [comment] 2022-08-09 15:43
@joliveirinha may have found a possible solution.

**Comment by Albonycal** [comment] 2022-08-10 09:38
:eyes: :crossed_fingers:

**Comment by Albonycal** [comment] 2022-08-19 18:32
Hey! has there been any progress on this issue? anything I can help with?
Thank you

**Comment by joliveirinha** [comment] 2022-08-20 12:06
Hi @Albonycal ,

We did some improvements, but looking at this issue, I don't know if they are related to the particular one you mention here.

Looking at the logs, as @sudarshan-reddy  mentioned, it just seems that eyeball left before the request finished. 
We are doing a release next week, let's see if any of the fixes actually helped here.

**Comment by don4of4** [comment] 2022-08-24 20:35
> > I am using the --protocol http2 flag because quic doesn't work
> 
> Can you explain what you mean by `doesn't work`? We'll need a little more information to help you. :)
> 

I am going to raise my hand and say we have been very frustrated by this and a _litany_ of issues with the tunnel recently.  We were seeing requests truncated (return 200), but have no body, causing P1 downstream issues since standard retry logic wasn't activated.  We saw issues under `2022.4.1` and `2022.8.2` 

@tomhuang12 is working with support under ticket 2535568 -- but please let us know what we can do to support.  We would like to see this stabilized ASAP.

**Comment by Albonycal** [comment] 2022-08-25 10:28
If it helps, when I say it "stops serving requests" it doesn't return the tunnel error or 503, the requests gets timed out

**Comment by Albonycal** [comment] 2022-09-17 16:48
This still happens :(

**Comment by morpig** [comment] 2022-11-08 13:27
can confirm this still happens. running cloudflared v2022.10.3 in kubernetes setup w/ http2 protocol set.

can send some CF-rays through ticket or here if needed.

**Comment by joliveirinha** [comment] 2022-11-10 19:29
Hi @morpig ,

Does this also happens when using QUIC?

Also, when this happens the next time can we get:
1) heap dump: run curl [http://localhost:PORT/debug/pprof/heap](http://localhost:50000/debug/pprof/heap) > heap.out
2) goroutine dump: run curl [http://localhost:PORT/debug/pprof/goroutine\?debug\=2](http://localhost:41227/debug/pprof/goroutine/?debug\=2) > goroutines.out
3) cpu profile: run curl [http://localhost:PORT/debug/pprof/profile\?seconds\=9](http://localhost:50000/debug/pprof/profile/?seconds\=9) > profiling.out

PORT should be the metrics port. Make sure you setup on in the configuration, otherwise you will need to check the logs when the service starts to find what port was used.

**Comment by morpig** [comment] 2022-11-12 00:32
@joliveirinha, QUIC looks okay but experiencing #735. let's continue there

**Comment by baptistejamin** [comment] 2022-12-21 13:37
Hey @joliveirinha we are currently experiencing the same issue in production. We are using QUIC as well and connections are extremely slow in some countries as we speak.

I have the heap.out ,  goroutines.out and profiling.out for you :)

**Comment by abelinkinbio** [comment] 2022-12-21 14:18
@baptistejamin thank you for taking the time to grab those logs. While they're fresh, would you mind opening a support ticket and linking this thread in the ticket? Once you've created that ticket, please share the ticket number here and we'll make sure it gets escalated directly to engineering so that we can continue the investigation. This should be really helpful.

**Comment by abelinkinbio** [comment] 2022-12-21 14:23
It looks like the previous ticket you filed has been closed. If it's easy to re-open that ticket then that works great as well. If not, then you should be able to just open a new ticket and we'll link the two internally so that we don't lose any context 👍

**Comment by baptistejamin** [comment] 2022-12-21 14:23
Sure. Ticket is 2650954

**Comment by abelinkinbio** [comment] 2022-12-21 14:43
Awesome. Thank you. I've asked for this to be escalated so we should be able to gain access to the logs files you shared shortly.

**Comment by Albonycal** [comment] 2022-12-21 16:35
An Update on my end: My ISP recently rolled out IPv6 support and I found out that if I force cloudflared to use IPv6 the tunnel is stable. So maybe NAT is to blame for the unstable tunnel? I don't know.

**Comment by baptistejamin** [comment] 2022-12-21 16:48
On our end, we strongly believe it's not related to cloudflared itself, but more related to the internal backbone. For instance congestion between Cloudflare Pops. It happened 3 times in the past. The `Incoming request ended abruptly` are just the results of 30 seconds timeouts

**Comment by Albonycal** [comment] 2022-12-21 16:51
congestion between Cloudflare Pops? that's quite unlikely

**Comment by baptistejamin** [comment] 2022-12-21 16:57
It happened a few times already in Finland, Germany, and Israel, and now India for us. It was undetected for a few days, and CF support confirmed peering issues a few days later. So I wouldn't be surprised at all. Especially because the tunnels in this specific case are stopping randomly and traffic goes unstable only for our customers in specific areas, while it works fine when they use a VPN

**Comment by Albonycal** [comment] 2022-12-21 17:00
Do you use CF Load Balancing for that? and can you provide the details about peering issues, with which ASNs? I'm on AS24560

**Comment by baptistejamin** [comment] 2022-12-21 17:06
Our core infrastructure is located in Amsterdam, DigitalOcean. However, since yesterday, our customers based in India are complaining they are struggling to connect to our apps. Our cloudflared instances are proxied to AMS, FRA or LON. 

We are seeing a lot of `Incoming request ended abruptly: context canceled` errors since yesterday for our users connected in India. As those users can connect to their local CF POP (BOM for instance), and our system is connected successfully to AMS, FRA and LON, it likely means there is an issue between those Cloudflare pops.

**Comment by KawaKode** [comment] 2023-01-10 15:11
Hello, 
I have the same issue, where I get the exact same errors as @Albonycal with my tunnels suddenly not resolving after a while.
in the meantime, I made a little cron job to restart cloudflared every 30 minutes as when it restarts, I get tunnel connectivity. 
I'm in France, if that helps.

**Comment by joliveirinha** [comment] 2023-01-10 19:48
@KawaKode can you gather an heap dump and go routine dump when this happens?

Also, additionally it would also help if you can provide the file descriptors associated with the cloudflared process.
 `lsof`
 
 @baptistejamin have you provided the files in the zendesk ticket? I am been informed that the the ticket wasn't updated.

**Comment by baptistejamin** [comment] 2023-01-10 22:23
@joliveirinha I attached the files to the Zendesk ticket, however, it is highly possible the files were dropped.

The ticket was closed so feel free to send an email to baptiste@crisp.chat and I'll forward the dump.

It was confirmed our issue wasn't related to Cloudflared, but was caused by a peering issue between two Cloudflare edges. 

It seems under such conditions, Cloudflared is not handling properly.

**Comment by KawaKode** [comment] 2023-01-11 09:14
I think I know what caused my issues : I have two machines on different networks (my local server and my VPS) and they both had cloudflared on them configured on the same tunnel, I removed the VPS from that and now it works like a charm.

**Comment by joliveirinha** [comment] 2023-01-11 09:55
ok. Since this thread has already several sub-threads and problems/solutions, I am going to close it for now.
Feel free to re-open, or better yet, open a new one so we don't lose the focus on the specific problem.

Again thanks for the reports and help.

**Closed by joliveirinha** 2023-01-11 09:55 UTC
Labels: Type: Bug, Priority: Normal

**Comment by WangWenBin2017** [comment] 2023-05-03 09:28
I have two servers located in North Carolina and Germany. I encountered the same issue using Debian 11 and the latest version of Cloudflared (2023.5.0). With the same configuration, the server in Germany can establish a gRPC connection using "--protocol quic", but the server in North Carolina doesn't work and requires "--protocol http2" or "h2mux" to function. I've tried switching tunnel versions (--edge-ip-version 6/4), but it didn't help.

@cynorfleet You're right. In my case, the server in Germany proxies traffic from localhost:1234, while the server in North Carolina proxies traffic from 10.0.0.100:1234 instead of localhost. I believe this could be a bug.

**Comment by mrexodia** [comment] 2023-06-02 15:16
This issue still seems relevant. When I use `http://localhost:80` everything works, but when I use `http://api.internal.lan:80` (which is running on the same machine) I always get an empty response.

**Comment by Flumeded** [comment] 2023-10-27 23:58
> I have two servers located in North Carolina and Germany. I encountered the same issue using Debian 11 and the latest version of Cloudflared (2023.5.0). With the same configuration, the server in Germany can establish a gRPC connection using "--protocol quic", but the server in North Carolina doesn't work and requires "--protocol http2" or "h2mux" to function. I've tried switching tunnel versions (--edge-ip-version 6/4), but it didn't help.
> 
> @cynorfleet You're right. In my case, the server in Germany proxies traffic from localhost:1234, while the server in North Carolina proxies traffic from 10.0.0.100:1234 instead of localhost. I believe this could be a bug.

It appears to be the case.
I'm running traefik though.

I changed rule from redirect from homeassistant.local:8123 to IP:8123 (e.g. 192.168.0.100:8123) and that resolved the issue

**Comment by mailinglists35** [comment] 2024-03-13 17:57
I've got this message when I accidentally forgot some *PROXY variables turned on during creating the container, which propagated to the cloudflared inside the container which was attempting to connect to the origin via the proxy.
