### ISSUE TITLE
Cloudflared is not handling gracefully after CF detected DDoS attack 🐛

### ISSUE THREAD

**Issue by baptistejamin** [cloudflare/cloudflared#701] opened 2022-07-20 09:44 UTC
**Describe the bug**

We had today an issue with our Cloudflared daemons. It seems there was a DDoS attack (detected by Cloudflare) that was proxied to the tunnels.

However, the Cloudflared tunnels were stuck and had to be restarted so the traffic could run properly.

![image](https://user-images.githubusercontent.com/866499/179951413-5ff217f9-7d6e-415d-9c03-ffb62e52c07d.png)

![image](https://user-images.githubusercontent.com/866499/179951475-b39dc5c8-d4dc-45d8-8c28-816b3a08fa8f.png)

![image](https://user-images.githubusercontent.com/866499/179951556-1a15b2e5-6c40-43f6-bf74-233613b7461f.png)

**Expected behavior**

Cloudflared daemons should be able to recover their states without having to be restarted.

**Environment and versions**
 - OS: Debian 11
 - Architecture: Intel
 - Version: Cloudflared 2022.7.1

**Logs and errors**

Logs are full of errors like this
```
Jul 20 05:32:00 edge-1 cloudflared[11884]: 2022-07-20T09:32:00Z ERR  error="Error writing response header: stream 46913 canceled with error code 0" cfRay=XXXXXXXXXXX-SIN originService=http://127.0.0.1:80
Jul 20 05:32:00 edge-1 cloudflared[11884]: 2022-07-20T09:32:00Z ERR Request failed error="Error writing response header: stream 46913 canceled with error code 0" connIndex=3 dest=XXXXXXXXXX ip=XX.XX.XX.XX type=http
Jul 20 05:32:00 edge-1 cloudflared[11884]: 2022-07-20T09:32:00Z ERR Failed to handle QUIC stream error=EOF connIndex=3 ip=XX.XX.XX.XX
Jul 20 05:32:00 edge-1 cloudflared[11884]: 2022-07-20T09:32:00Z ERR Failed to handle QUIC stream error=EOF connIndex=3 ip=XX.XX.XX.XX
Jul 20 05:32:00 edge-1 cloudflared[11884]: 2022-07-20T09:32:00Z ERR Failed to handle QUIC stream error=EOF connIndex=3 ip=XX.XX.XX.XX
Jul 20 05:32:00 edge-1 cloudflared[11884]: 2022-07-20T09:32:00Z ERR Failed to handle QUIC stream error=EOF connIndex=3 ip=XX.XX.XX.XX
```

**Additional context**

**Comment by sudarshan-reddy** [comment] 2022-07-20 10:21
Hey @baptistejamin. The 503s indicate that cloudflared unregistered itself from our edge. Do you have any indication of this cloudflared attempting to `reconnect` or saying `connection lost` in your logs?

**Comment by sudarshan-reddy** [comment] 2022-07-20 10:34
I might need your `tunnel_id` to debug this further.  This is just an identifier and we won't know any of your secrets. You could share it here or also open a support ticket with us to further track this to completion.

**Comment by baptistejamin** [comment] 2022-07-20 10:35
We can submit the `tunnel_id` in the ticket 2506146.

**Comment by abelinkinbio** [comment] 2022-07-20 21:26
@baptistejamin thank you for the additional context, timestamps, and logs surrounding this issue. Looks like our support team has already picked this up and we'll continue the investigation there. I'll close this out, but please feel free to re-open if you need additional support.

**Closed by abelinkinbio** 2022-07-20 21:26 UTC
Labels: Type: Bug, Priority: Normal

**Comment by sudarshan-reddy** [comment] 2022-08-26 06:50
Hey @baptistejamin ! Thanks for being super patient with this.

We were tracking this as a potential duplicate of https://github.com/cloudflare/cloudflared/issues/698

A possible fix will be out in the next release.

**Comment by amalcev** [comment] 2024-12-13 04:50
It's still not fixed

**Comment by mlanies** [comment] 2024-12-13 14:50
> It's still not fixed

You can temporarily restart the server yourself using a script in case of an attack. Additionally, through the Cloudflare API, you can retrieve data about incidents and update Zero Trust URLs, as well as switch to stricter WAF settings until the cause and method of the attack are identified.
