### ISSUE TITLE
🐛GRPC connection failed with quic protocol

### ISSUE THREAD

**Issue by hezhijie0327** [cloudflare/cloudflared#1170] opened 2024-01-30 13:55 UTC
**Describe the bug**
When run with `--protocol auto` or `--protocol quic`, and connecting to GRPC, got error message
```
2024-01-30T13:49:11Z ERR error="Incoming request ended abruptly: context canceled" cfRay=84da2cf27ef82aab-LAX event=1 ingressRule=1 originService=https://127.0.0.1:8443
2024-01-30T13:49:11Z ERR Request failed error="Incoming request ended abruptly: context canceled" connIndex=0 dest=https://subdomain.mydomain.com/gRPC/Tun event=0 ip=198.41.192.27 type=http
```
But after switch to `--protocol http2`, no issue

**To Reproduce**
1. Set `--protocol auto` or `--protocol quic`
2. Run with docker
3. See error

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : `626ee7b1-b412-4b83-9ecd-1d84bb0e8b5a`
5. cloudflared config: 

**Expected behavior**
run with `--protocol http2` can access GRPC

**Environment and versions**
 - OS: [e.g. MacOS] Ubuntu 22.04 LTS
 - Architecture: [e.g. AMD, ARM] AMD64
 - Version: [e.g. 2022.02.0] 2024.1.5

**Logs and errors**
If applicable, add logs or errors to help explain your problem.

**Additional context**

**Comment by bt90** [comment] 2024-02-04 15:06
https://github.com/quic-go/quic-go/issues/2266

**Comment by joliveirinha** [comment] 2024-02-06 14:11
This is not a bug. We officially don't support GRPC.
We did some work to have it working on HTTP2 for testing purposes, but due to prioritisation, this feature is not supported.

The main reason is because we don't really support HTTP trailers in QUIC (which is a requirement for gRPC). 
So, I will close this for now, since there is already another issue open to track this.

**Closed by joliveirinha** 2024-02-06 14:11 UTC
Labels: Type: Bug, Priority: Normal
