### ISSUE TITLE
Linux/armhf binary

### ISSUE THREAD

**Issue by ItalyPaleAle** [cloudflare/cloudflared#359] opened 2021-04-21 21:24 UTC
With #115, binaries have been published for Linux/armv6 and Linux/arm64. Would it be possible to have binaries for armhf (ie. armv7) too?

armhf is what is currently used on RPi 3/4 running in 32-bit. The existing arm (armv6) binary won't launch on that:

```sh
root@raspberrypi:~# uname -a
Linux raspberrypi 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux
root@raspberrypi:~# dpkg -i cloudflared-stable-linux-arm.deb
dpkg: error processing archive cloudflared-stable-linux-arm.deb (--install):
 package architecture (arm) does not match system (armhf)
Errors were encountered while processing:
 cloudflared-stable-linux-arm.deb
```

**Comment by nikolaishields** [comment] 2021-04-22 17:39
Tangentially related, what about binaries for armv7?
It would be really cool to run this on openwrt based routers!

**Comment by ItalyPaleAle** [comment] 2021-04-22 17:41
For Linux, generally armhf == armv7

**Comment by nikolaishields** [comment] 2021-04-22 18:27
@ItalyPaleAle thanks for the clarification, I've been trying to make heads or tails of all of the arm prefixes in build args.
for what its worth, building with these args worked for me, although since its a dev build I'm getting x509 errors when trying to do just about anything:
`GOOS=linux GOARCH=arm GOARM=7 go build -v -x github.com/cloudflare/cloudflared/cmd/cloudflare`

**Comment by nikolaishields** [comment] 2021-04-22 18:32
> @ItalyPaleAle thanks for the clarification, I've been trying to make heads or tails of all of the arm prefixes in build args.
> for what its worth, building with these args worked for me, although since its a dev build I'm getting x509 errors when trying to do just about anything:
> `GOOS=linux GOARCH=arm GOARM=7 go build -v -x github.com/cloudflare/cloudflared/cmd/cloudflare`

That's not entirely true. It all works, tunnels and what not but it obviously fails to auto-update and automatically do the cert exchange. The ideal solution being a supported release of armhf.

**Comment by nikolaishields** [comment] 2021-04-22 18:32
> My biggest problem with building from source is that I have to manually track upgrades and re-build every time. Given how this is a security tool, I would prefer to have official builds and upgrade more simply.

Completely agree.

**Comment by IndraGunawan** [comment] 2021-05-31 10:04
i'm using this build for armhf arch https://hobin.ca/cloudflared/

**Comment by viggy28** [comment] 2021-05-31 13:36
Recently, I had to run armv7 and found this docker image helpful https://github.com/homeall/cloudflared

Agree, it would be nice to have an official docker image also supporting that. (Don't see that https://hub.docker.com/r/cloudflare/cloudflared/tags?page=1&ordering=last_updated or am I missing it)

**Comment by Misly16** [comment] 2021-07-31 22:21
any updated on this?

**Comment by benbalter** [comment] 2021-08-02 20:48
I was able to get [the latest official release package](https://github.com/cloudflare/cloudflared/releases) to install on `armv7l`. To do this, I adapted [the official install instructions for linux](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation#linux), by [adding `arm` as a supported `dpkg` architecture](https://monicagranbois.com/blog/raspberrypi/error-package-architecture-arm-does-not-match-system-armhf/):

```
$ wget -q https://github.com/cloudflare/cloudflared/releases/download/2021.8.0/cloudflared-linux-arm.deb
$ sudo dpkg --add-architecture arm
$ sudo dpkg -i cloudflared-linux-arm.deb
...
$ cloudflared version
cloudflared version 2021.8.0 (built 2021-08-02-0921 UTC)
```

I don't know if this is the "right" way to do it (the above-linked article documented some possible side effects), but it installed and ran without error.

**Comment by gabrielwhite** [comment] 2021-08-10 22:18
I'd love to see an official armv7 docker image for cloudflared.

**Comment by sudarshan-reddy** [comment] 2021-08-11 08:52
https://github.com/cloudflare/cloudflared/releases/download/2021.8.2/cloudflared-linux-arm should work on rpi 3-4 32 bit systems.

**Comment by jauderho** [comment] 2021-08-11 09:22
So I've built a pretty minimal set of images here with a variety of supported platforms: https://hub.docker.com/r/jauderho/cloudflared/tags?page=1&ordering=last_updated

Dockerfile is here: https://github.com/jauderho/dockerfiles/blob/main/cloudflared/Dockerfile

And lastly, new images will be built no later than an hour after cloudflare tags a new release. =D

**Comment by MW420BLAZEIT** [comment] 2021-10-17 09:51
Any updates on this ? 
I'm still unable to install arm binary packages on my raspberry pi which is armv7
![image](https://user-images.githubusercontent.com/38746256/137621888-97ef5723-109b-4ff3-8afd-c7ee519a636e.png)

**Comment by sudarshan-reddy** [comment] 2021-10-17 12:44
https://github.com/cloudflare/cloudflared/issues/441

**Comment by sudarshan-reddy** [comment] 2021-10-17 12:46
Can you try https://github.com/cloudflare/cloudflared/releases/download/2021.10.3/cloudflared-linux-arm64.deb as well and let me know if that works?

**Comment by basert** [comment] 2021-10-18 21:06
Running into the same issue on my Rasperry Pi 4:
```
pi@raspberrypi:~ $ hostnamectl
   Static hostname: raspberrypi
         Icon name: computer
        Machine ID: <id>
           Boot ID: <id>
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 5.10.52-v7l+
      Architecture: arm
```

**Comment by Kate222** [comment] 2021-11-08 05:47
I have recently successfully run a tunnel with rpi 4B 8G using :
 wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm
sudo cp ./cloudflared-linux-arm /usr/local/bin/cloudflared
sudo chmod +x /usr/local/bin/cloudflared
cloudflared -v

The version is 2021.10.5

I use raspberry os 32bit lite version.

**Comment by neo-neo1** [comment] 2021-12-29 15:18
Strange how [official Cloudflared](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation) arm binary works for armhf (armv7l) but .deb file errors out at `package architecture (arm) does not match system (armhf)` 

Unfortunately it seems properly unversal arm support is not a priority for Cloudflare.

**Comment by netty0** [comment] 2022-01-07 05:22
> Strange how [official](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation) cloudflared-linux-arm binary file works for ARMHF (ARMV7L) but cloudflared-linux-arm.deb file errors out at `package architecture (arm) does not match system (armhf)`
> 
> Unfortunately it seems properly universal ARM support is not a priority for Cloudflare.

I can confirm this 100%. I wonder how many more months we'll need to manually download the binary for every update because the .deb doesn't work

**Comment by patricegautier** [comment] 2022-04-16 19:48
+1..

**Comment by balupton** [comment] 2022-04-17 01:04
This issue should be renamed to a request for the 32 bit arm binary, as the provided arm binary has been working fine since its release on 64 bit arm operating systems.

**Comment by austonpramodh** [comment] 2022-04-24 05:13
+1. I was trying to install cloudflared on beaglebone black.

**Comment by sudarshan-reddy** [comment] 2022-06-20 14:12
We now support armhf on github releases.

Can you try 

```
wget https://github.com/cloudflare/cloudflared/releases/download/2022.6.3/cloudflared-linux-armhf.deb
sudo dpkg -i ./cloudflared-linux-armhf.deb
```

now?

**Comment by sudarshan-reddy** [comment] 2022-06-20 16:43
What's your `uname -a`?

**Comment by flavioheleno** [comment] 2022-06-20 16:43
```Linux dns 5.15.32+ #1538 Thu Mar 31 19:37:58 BST 2022 armv6l GNU/Linux```

**Comment by sudarshan-reddy** [comment] 2022-06-20 16:45
I think this means we will have to have an `armel` release as well. Debian only supports `armhf` for `armv7l` and above AFAIK

**Comment by flavioheleno** [comment] 2022-06-20 17:12
oh, ok :) thank you @sudarshan-reddy!

**Comment by patricegautier** [comment] 2022-06-20 18:46
Hi there, still similar symptoms for Raspbian Bullseye..

5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

Thanks!

	-P

**Comment by sudarshan-reddy** [comment] 2022-06-20 23:47
Yours is a 64 bit system. You should use the arm64 variant.

**Comment by sudarshan-reddy** [comment] 2022-06-21 14:53
Does anyone with an armv7l system have troubles installing from this `.deb` file? If not, I will close this issue.

**Comment by flavioheleno** [comment] 2022-06-21 18:57
shall I open a new issue for `armel` releases, @sudarshan-reddy?

**Comment by sudarshan-reddy** [comment] 2022-06-21 19:03
Agreed. Let's open a separate issue to track `armel` based requests.

**Closed** 2022-06-21 21:03 UTC

**Comment by patricegautier** [comment] 2022-10-11 09:08
Mm.. I have still getting:

exec /usr/local/bin/cloudflared: exec format error

And docker-compose doesn’t seem to support the explicit directive:

platform: “linux/arm64” 


ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.cloudflared: 'platform'


Shouldn’t the right platform be selected by default anyway?   I don’t have to specify the platform for any other container..

	-P

**Comment by steinauf85** [comment] 2023-03-08 15:57
> Does anyone with an armv7l system have troubles installing from this `.deb` file? If not, I will close this issue.

Using a Pi 4B (armhf / armv7) I attempted yesterday to install from the arm32bit .deb (https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm.deb). No dice. I see i'm not the only one who's had this issue, but I also see comments claiming that these issues have been resolved or closed. Not sure if I'm missing or doing something wrong here or if this has resurfaced.

```
dpkg: error processing archive cloudflared.deb (--install):
 package architecture (arm) does not match system (armhf)
Errors were encountered while processing:
 cloudflared.deb
```
