### ISSUE TITLE
Internet Blips / How to deal with connection drops

### ISSUE THREAD

**Issue by animosity22** [cloudflare/cloudflared#278] opened 2020-12-11 18:13 UTC
I've been trying to figure out the best way to deal with rebooting my router or something along those lines that causes a brief internet disruption. I've tried to increase retries to see if that helps, but doesn't seem to do much.

The error is along the lines of:

```
[2020-12-11T11:39:16.860760386-05:00]: Serve tunnel error: Application error: 3002 connection dropped
```

Which to me says the tunnel is down, but the service never fails/stops so systemd doesn't restart it and it just remains there until I manually restart it.

I can scrap the log and kick off some automation around the issue but was wondering if there was a better way to deal with automating the restart of the service or another flag/option I may have missed in reading through the documentation.

**Comment by danielewood** [comment] 2020-12-12 05:29
> I can scrap the log and kick off some automation around the issue but was wondering if there was a better way to deal with automating the restart of the service or another flag/option I may have missed in reading through the documentation.

I experienced issues with my own [wrapper script for tunneling Plex](https://github.com/danielewood/plexargod) needing to read the state of cloudflared. What I did was add my own script as an ExecStartPost to the service file with a curl loop, polling the built in [metrics server](https://github.com/cloudflare/cloudflared/issues/169).  On any failure condition, I `exit 1`, which causes systemd to restart the entire service.

Just add something like:
```yaml
metrics: localhost:33400
```
to your config.yml and it will start/bind a metrics server there.

**Comment by animosity22** [comment] 2020-12-12 12:42
Thanks as I was hoping to see if there was a way that I was not seeing within the daemon itself as if the connection drop, it should exit itself as it really isn't doing anything.

Just seems strange that the ingress rules and the 'enterprise' level things are there but no way to handle failures itself.

I already have it setup to restart via monit basically the same way as I just look for connection dropped in the log I already have setup.

```
check file argolog with path /var/log/argo.log
    start program = "/usr/bin/systemctl start argo"
    stop program = "/usr/bin/systemctl stop argo" with timeout 120 seconds
    if match dropped then restart
```

**Comment by chungthuang** [comment] 2020-12-14 10:07
Hi @animosity22, cloudflared should reestablish your connections. What version are you using? In version 2020.12.0 we added a new `/ready` endpoint to the metrics server that returns 200 if at least 1 connection is up, and 503 otherwise.

**Comment by animosity22** [comment] 2020-12-14 17:07
I am on:

```
./cloudflared --version
cloudflared version 2020.12.0 (built 2020-12-08-2302 UTC)
```

I can simulate the issue with rebooting my router which creates ~1 minute network outage at which time any outbound traffic along with DNS would fail.

what would the retries look like in the log? All I see is the dropped messages.

I'll check the endpoint as well as that would be a little nicer than the logs.

**Comment by chungthuang** [comment] 2020-12-15 09:54
It will look like `Connection x registered with`.

**Comment by animosity22** [comment] 2020-12-15 11:33
A reboot of my router for ~45 seconds of Internet outages causes it never to recover:

```
[2020-12-15T11:32:05.209195797Z]: mux - metrics: Stopping mux metrics updater
[2020-12-15T11:32:05.213660221Z]: Serve tunnel error: Application error: 3002 connection dropped
[2020-12-15T11:32:05.215002249Z]: Retrying connection 0 in 1s seconds, error Application error: 3002 connection dropped
[2020-12-15T11:32:06.488653908Z]: Serve tunnel error: cannot replace existing connection
[2020-12-15T11:32:06.488691802Z]: Retrying connection 0 in 2s seconds, error cannot replace existing connection
[2020-12-15T11:32:06.489194934Z]: mux - metrics: Stopping mux metrics updater
[2020-12-15T11:32:17.216684719Z]: mux - metrics: Stopping mux metrics updater
[2020-12-15T11:32:17.216711223Z]: Serve tunnel error: Application error: 3002 connection dropped
[2020-12-15T11:32:18.312885434Z]: mux - metrics: Stopping mux metrics updater
[2020-12-15T11:32:18.312919545Z]: Serve tunnel error: Application error: 3002 connection dropped
[2020-12-15T11:32:21.031130862Z]: mux - metrics: Stopping mux metrics updater
[2020-12-15T11:32:21.031208217Z]: Serve tunnel error: Application error: 3002 connection dropped
```

**Comment by vidarak** [comment] 2020-12-28 13:45
Similar issues here. It is a pretty nasty bug for a service like this.

**Comment by animosity22** [comment] 2020-12-28 13:50
It's pretty strange that some basic retries or the service actually stopping so systemd can take care of it doesn't work.

```
[2020-12-28T00:59:13.573650506-05:00]: mux - metrics: Stopping mux metrics updater
[2020-12-28T00:59:13.574582848-05:00]: Serve tunnel error: muxer shutdown
[2020-12-28T00:59:13.574705289-05:00]: Retrying connection 2 in 1s seconds, error muxer shutdown
[2020-12-28T00:59:14.740678064-05:00]: Serve tunnel error: cannot replace existing connection
[2020-12-28T00:59:14.74072386-05:00]: Retrying connection 2 in 2s seconds, error cannot replace existing connection
[2020-12-28T00:59:14.741471387-05:00]: mux - metrics: Stopping mux metrics updater
[2020-12-28T03:44:19.38847934-05:00]: mux - read: EOF: connection closed unexpectedly
[2020-12-28T03:44:19.388595249-05:00]: mux - metrics: Stopping mux metrics updater
```

Just kind of breaks if it loses connection for a 10-20 seconds.

**Comment by bittylicious** [comment] 2021-01-11 12:17
We've had issues that mirror the above. Generally we fully lose the connection to the tunnel, but cloudflared doesn't reestablish the connection or even quit.

We've written a watchdog daemon that hopefully will restart the daemon. If anyone wants to use or improve this, feel free. I am placing this in the public domain.

```
#!/bin/bash

# Get cloudflared first PID
pid=$(pidof -s cloudflared)

# If no pid, just start cloudflared and end
if [ -z "$pid" ]; then
    echo "No process running so starting"
    (/usr/local/bin/cloudflared --config /etc/cloudflared/config.yml --no-autoupdate tunnel run) &
    exit 0
fi

# Get process age and don't do anything if less than 5 minutes old. xargs on its own acts like trim()
seconds=$(ps -p ${pid} -o etimes= | xargs)
if [ "${seconds}" -lt 300 ]; then
    echo "too young"
    exit 0
fi

# Get status from metrics server
status=$(curl -s http://localhost:8099/ready | jq -r '.status')

# If status is 503, we don't have any active connections so restart
if [ "${status}" == "503" ]; then
    echo "cloudflared appears to be down, restarting"
    killall cloudflared

    # Wait two minutes
    sleep 120

    # And then kill them all just in case
    killall -9 cloudflared

    # And restart
    (/usr/local/bin/cloudflared --config /etc/cloudflared/config.yml --no-autoupdate tunnel run) &
    exit 0
fi

# Everything is runing, so nothing to do
exit 0
```

**Comment by vidarak** [comment] 2021-01-11 14:14
On a related note: there is a non-working retries option to the arguments/config. I've tried defining it in the config but the log file doesn't indicate that it has read the option. The amount of times a connection is retried is varying a lot. It seems to give up immediately. I wonder when Cloudflare will fix this mess? @chungthuang

**Comment by vidarak** [comment] 2021-01-13 00:56
I learned today that version 2012.12.0 has severe issues with connection stability. Need to use 2012.11.11 instead for now.

**Comment by bittylicious** [comment] 2021-01-13 10:43
Cloudflare tech support were able to reproduce this, which is good news at least.

**Comment by TownLake** [comment] 2021-01-13 13:58
Hi everyone, sorry for the delay here. We've found the issue on our side and are releasing a new version of `cloudflared` later today to address this. Thanks for the reports and feedback. We'll update this thread when that release is ready.

**Comment by TownLake** [comment] 2021-01-13 18:02
We've released a new version of `cloudflared`, `2020.1.0`, that includes a fix for this issue. We'll keep this issue open while folks test, please let us know if upgrading solves it for you. Thanks for your patience.

**Comment by nmldiegues** [comment] 2021-01-13 18:04
> We've released a new version of cloudflared, 2020.1.0, that includes a fix for this issue.
This meant `2021.1.0`.

We've had an internal issue that prevented the release to make it to Equinox. So we'll have another `2021.1.1` out today.

**Comment by nmldiegues** [comment] 2021-01-13 18:39
`2021.1.1` is now out, so all platforms should be covered.

Please upgrade and let us know.

**Comment by adamchalmers** [comment] 2021-02-03 23:56
We believe this was a regression with 2020.12.0 that should be fixed in any 2021.x.y release. We accidentally introduced a deadlock that was triggered when the connections had reconnected more than a certain number of times. Because it took several reconnects to cause the deadlock, it didn't get surfaced during testing. We've refactored the offending code to ensure it doesn't deadlock anymore. Please reopen if this reoccurs. Thanks!

**Closed by adamchalmers** 2021-02-03 23:56 UTC
