### ISSUE TITLE
🐛 Latest AMD 64 release is not available for latest release

### ISSUE THREAD

**Issue by skyhawk14** [cloudflare/cloudflared#1103] opened 2023-11-08 03:21 UTC
**Describe the bug**
While downloading cloudflare from the documentation link it is unable to do it for the latest release.
Also while installing using homebrew it is installing the 23.8.2(previous version)

**To Reproduce**
1. Try to access https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-amd64.tgz 

**Expected behavior**
Should be able to download and install the latest cloudflare version.

**Environment and versions**
 - OS: MacOS
 - Architecture: AMD
 - Version: 2023.10.0

**Comment by Nezteb** [comment] 2023-11-08 04:14
Duplicate of https://github.com/cloudflare/cloudflared/issues/1094.

**Comment by sudarshan-reddy** [comment] 2023-11-13 17:22
Should be fixed now. Lets continue tracking inn 1094.

**Closed by sudarshan-reddy** 2023-11-13 17:22 UTC
Labels: Type: Bug, Priority: Normal
