### ISSUE TITLE
http2 response writer panic

### ISSUE THREAD

**Issue by milgradesec** [cloudflare/cloudflared#552] opened 2022-01-20 19:52 UTC
```logs
2022-01-20T19:02:09Z INF Unregistered tunnel connection connIndex=2
2022-01-20T19:02:09Z INF Lost connection with the edge connIndex=2
2022-01-20T19:02:09Z WRN Serve tunnel error error="connection with edge closed" connIndex=2
2022-01-20T19:02:09Z INF Retrying connection in up to 1s seconds connIndex=2
Recover from http2 response writer panic, error goroutine 184115 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x88
github.com/cloudflare/cloudflared/connection.(*http2RespWriter).Write.func1()
	/go/src/github.com/cloudflare/cloudflared/cloudflared/connection/http2.go:236 +0x38
panic({0xa28580, 0xd497d0})
	/usr/local/go/src/runtime/panic.go:1038 +0x224
golang.org/x/net/http2.(*responseWriter).write(0x4000118710, 0x78, {0x4000327000, 0x78, 0x1000}, {0x0, 0x0})
	/go/src/github.com/cloudflare/cloudflared/cloudflared/vendor/golang.org/x/net/http2/server.go:2700 +0x1ac
golang.org/x/net/http2.(*responseWriter).Write(0x4000118710, {0x4000327000, 0x78, 0x1000})
	/go/src/github.com/cloudflare/cloudflared/cloudflared/vendor/golang.org/x/net/http2/server.go:2689 +0x48
github.com/cloudflare/cloudflared/connection.(*http2RespWriter).Write(0x40002fbd40, {0x4000327000, 0x78, 0x1000})
	/go/src/github.com/cloudflare/cloudflared/cloudflared/connection/http2.go:239 +0x70
zombiezen.com/go/capnproto2/rpc.(*streamTransport).SendMessage(0x4000433740, {0xd6e018, 0x40002fbd80}, {{0x40006504e0, 0x8, {0x8, 0x1}, 0xffffffffffffffff, 0x0}})
	/go/src/github.com/cloudflare/cloudflared/cloudflared/vendor/zombiezen.com/go/capnproto2/rpc/transport.go:65 +0x12c
github.com/cloudflare/cloudflared/tunnelrpc.(*transport).SendMessage(0x400008cd68, {0xd6e018, 0x40002fbd80}, {{0x40006504e0, 0x8, {0x8, 0x1}, 0xffffffffffffffff, 0x0}})
	/go/src/github.com/cloudflare/cloudflared/cloudflared/tunnelrpc/logtransport.go:28 +0x110
zombiezen.com/go/capnproto2/rpc.(*Conn).dispatchSend(0x400027ec60)
	/go/src/github.com/cloudflare/cloudflared/cloudflared/vendor/zombiezen.com/go/capnproto2/rpc/transport.go:104 +0x14c
created by zombiezen.com/go/capnproto2/rpc.NewConn
	/go/src/github.com/cloudflare/cloudflared/cloudflared/vendor/zombiezen.com/go/capnproto2/rpc/rpc.go:115 +0x2c4

Recover from http2 response writer panic, error goroutine 184115 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x88
github.com/cloudflare/cloudflared/connection.(*http2RespWriter).Write.func1()
	/go/src/github.com/cloudflare/cloudflared/cloudflared/connection/http2.go:236 +0x38
panic({0xa28580, 0xd497d0})
	/usr/local/go/src/runtime/panic.go:1038 +0x224
golang.org/x/net/http2.(*responseWriter).write(0x4000118710, 0x28, {0x4000327000, 0x28, 0x1000}, {0x0, 0x0})
	/go/src/github.com/cloudflare/cloudflared/cloudflared/vendor/golang.org/x/net/http2/server.go:2700 +0x1ac
golang.org/x/net/http2.(*responseWriter).Write(0x4000118710, {0x4000327000, 0x28, 0x1000})
	/go/src/github.com/cloudflare/cloudflared/cloudflared/vendor/golang.org/x/net/http2/server.go:2689 +0x48
github.com/cloudflare/cloudflared/connection.(*http2RespWriter).Write(0x40002fbd40, {0x4000327000, 0x28, 0x1000})
	/go/src/github.com/cloudflare/cloudflared/cloudflared/connection/http2.go:239 +0x70
zombiezen.com/go/capnproto2/rpc.(*streamTransport).SendMessage(0x4000433740, {0xd6e018, 0x40002fbd80}, {{0x4000650570, 0x8, {0x8, 0x1}, 0xffffffffffffffff, 0x0}})
	/go/src/github.com/cloudflare/cloudflared/cloudflared/vendor/zombiezen.com/go/capnproto2/rpc/transport.go:65 +0x12c
github.com/cloudflare/cloudflared/tunnelrpc.(*transport).SendMessage(0x400008cd68, {0xd6e018, 0x40002fbd80}, {{0x4000650570, 0x8, {0x8, 0x1}, 0xffffffffffffffff, 0x0}})
	/go/src/github.com/cloudflare/cloudflared/cloudflared/tunnelrpc/logtransport.go:28 +0x110
zombiezen.com/go/capnproto2/rpc.(*Conn).dispatchSend(0x400027ec60)
	/go/src/github.com/cloudflare/cloudflared/cloudflared/vendor/zombiezen.com/go/capnproto2/rpc/transport.go:104 +0x14c
created by zombiezen.com/go/capnproto2/rpc.NewConn
	/go/src/github.com/cloudflare/cloudflared/cloudflared/vendor/zombiezen.com/go/capnproto2/rpc/rpc.go:115 +0x2c4
```

**Comment by milgradesec** [comment] 2022-01-20 19:54
Running Cloudflared on ARM64 (rpi4)

**Comment by nmldiegues** [comment] 2022-01-20 22:32
This is a duplicate of https://github.com/cloudflare/cloudflared/issues/450

In practice this should not be affecting the proxied traffic with any harm.

**Closed by nmldiegues** 2022-01-20 22:32 UTC
