### ISSUE TITLE
cant connect with quic while using a vpn

### ISSUE THREAD

**Issue by realivanjx** [cloudflare/cloudflared#528] opened 2021-12-14 05:55 UTC
hi. im trying to create a tunnel but i noticed that while im using a vpn (cyberghost on windows) im unable to connect with quic protocol. here is the log:
```
❯ cloudflared --url https://localhost:5001 --no-tls-verify
2021-12-14T05:49:22Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2021-12-14T05:49:22Z INF Requesting new quick Tunnel on trycloudflare.com...
2021-12-14T05:49:24Z INF +--------------------------------------------------------------------------------------------+
2021-12-14T05:49:24Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2021-12-14T05:49:24Z INF |  https://west-expansys-odds-ellis.trycloudflare.com                                        |
2021-12-14T05:49:24Z INF +--------------------------------------------------------------------------------------------+
2021-12-14T05:49:24Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp]
2021-12-14T05:49:24Z INF Version 2021.11.0
2021-12-14T05:49:24Z INF GOOS: windows, GOVersion: devel +a84af465cb Mon Aug 9 10:31:00 2021 -0700, GoArch: amd64
2021-12-14T05:49:24Z INF Settings: map[no-tls-verify:true protocol:quic url:https://localhost:5001]
2021-12-14T05:49:24Z INF cloudflared will not automatically update on Windows systems.
2021-12-14T05:49:24Z INF Generated Connector ID: a34f5de9-4a59-4eca-8e43-6843777e3e62
2021-12-14T05:49:25Z INF Initial protocol quic
2021-12-14T05:49:25Z INF Starting metrics server on 127.0.0.1:1036/metrics
2021-12-14T05:49:25Z INF cloudflared does not support loading the system root certificate pool on Windows. Please use --origin-ca-pool <PATH> to specify the path to the certificate pool
2021-12-14T05:49:25Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:62096->198.41.200.233:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:49:25Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:62096->198.41.200.233:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=0
2021-12-14T05:49:25Z INF Retrying connection in up to 2s seconds connIndex=0
2021-12-14T05:49:25Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:62097->198.41.200.233:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:49:25Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:62097->198.41.200.233:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=0
2021-12-14T05:49:25Z INF Retrying connection in up to 4s seconds connIndex=0
2021-12-14T05:49:27Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:62098->198.41.200.233:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:49:27Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:62098->198.41.200.233:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=0
2021-12-14T05:49:27Z INF Retrying connection in up to 8s seconds connIndex=0
2021-12-14T05:49:34Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:62099->198.41.200.233:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:49:34Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:62099->198.41.200.233:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=0
2021-12-14T05:49:34Z INF Retrying connection in up to 16s seconds connIndex=0
2021-12-14T05:49:36Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:62100->198.41.200.233:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:49:36Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:62100->198.41.200.233:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=0
2021-12-14T05:49:36Z INF Retrying connection in up to 32s seconds connIndex=0
2021-12-14T05:50:07Z INF Switching to fallback protocol http2 connIndex=0
2021-12-14T05:50:08Z INF Connection bf3ccb1a-8e1b-4ed6-8204-bbb30f17a006 registered connIndex=0 location=SIN
2021-12-14T05:50:08Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64351->198.41.192.47:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:08Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64351->198.41.192.47:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=1
2021-12-14T05:50:08Z INF Retrying connection in up to 2s seconds connIndex=1
2021-12-14T05:50:08Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64352->198.41.192.47:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:08Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64352->198.41.192.47:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=1
2021-12-14T05:50:08Z INF Retrying connection in up to 4s seconds connIndex=1
2021-12-14T05:50:09Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64353->198.41.192.47:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:09Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64353->198.41.192.47:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=1
2021-12-14T05:50:09Z INF Retrying connection in up to 8s seconds connIndex=1
2021-12-14T05:50:09Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64354->198.41.200.193:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:09Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64354->198.41.200.193:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=2
2021-12-14T05:50:09Z INF Retrying connection in up to 2s seconds connIndex=2
2021-12-14T05:50:09Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64355->198.41.200.193:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:09Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64355->198.41.200.193:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=2
2021-12-14T05:50:09Z INF Retrying connection in up to 4s seconds connIndex=2
2021-12-14T05:50:10Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64356->198.41.192.227:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:10Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64356->198.41.192.227:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=3
2021-12-14T05:50:10Z INF Retrying connection in up to 2s seconds connIndex=3
2021-12-14T05:50:11Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64357->198.41.192.227:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:11Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64357->198.41.192.227:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=3
2021-12-14T05:50:11Z INF Retrying connection in up to 4s seconds connIndex=3
2021-12-14T05:50:11Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64358->198.41.192.227:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:11Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64358->198.41.192.227:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=3
2021-12-14T05:50:11Z INF Retrying connection in up to 8s seconds connIndex=3
2021-12-14T05:50:12Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64359->198.41.200.193:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:12Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64359->198.41.200.193:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=2
2021-12-14T05:50:12Z INF Retrying connection in up to 8s seconds connIndex=2
2021-12-14T05:50:15Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64360->198.41.200.193:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:15Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64360->198.41.200.193:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=2
2021-12-14T05:50:15Z INF Retrying connection in up to 16s seconds connIndex=2
2021-12-14T05:50:16Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64361->198.41.192.47:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:16Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64361->198.41.192.47:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=1
2021-12-14T05:50:16Z INF Retrying connection in up to 16s seconds connIndex=1
2021-12-14T05:50:16Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64362->198.41.192.227:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:16Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64362->198.41.192.227:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=3
2021-12-14T05:50:16Z INF Retrying connection in up to 16s seconds connIndex=3
2021-12-14T05:50:16Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64363->198.41.192.227:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:16Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64363->198.41.192.227:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=3
2021-12-14T05:50:16Z INF Retrying connection in up to 32s seconds connIndex=3
2021-12-14T05:50:17Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64364->198.41.192.47:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:17Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64364->198.41.192.47:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=1
2021-12-14T05:50:17Z INF Retrying connection in up to 32s seconds connIndex=1
2021-12-14T05:50:20Z INF Switching to fallback protocol http2 connIndex=1
2021-12-14T05:50:22Z INF Connection a6ffc063-2272-49ce-b246-aa3c9d7eb2c7 registered connIndex=1 location=NRT
2021-12-14T05:50:26Z ERR Failed to create new quic connection, err: failed to dial to edge: INTERNAL_ERROR: write udp [::]:64365->198.41.200.193:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2021-12-14T05:50:26Z ERR Serve tunnel error error="failed to dial to edge: INTERNAL_ERROR: write udp [::]:64365->198.41.200.193:7844: wsasendto: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself." connIndex=2
2021-12-14T05:50:26Z INF Retrying connection in up to 32s seconds connIndex=2
2021-12-14T05:50:27Z INF Switching to fallback protocol http2 connIndex=3
2021-12-14T05:50:34Z INF Connection 198b4c24-f6fd-418e-a8ba-25d367bcb71b registered connIndex=3 location=NRT
2021-12-14T05:50:51Z INF Switching to fallback protocol http2 connIndex=2
2021-12-14T05:50:59Z INF Connection e87b07a4-381e-41a2-acf6-e6f1e9e2be8a registered connIndex=2 location=SIN
```

is this to be expected? thanks.

**Comment by nmldiegues** [comment] 2021-12-14 10:09
Duplicate of https://github.com/cloudflare/cloudflared/issues/496

**Closed by nmldiegues** 2021-12-14 10:09 UTC
