### ISSUE TITLE
Cloudflared installation on windows deletes PATH systemvariables

### ISSUE THREAD

**Issue by philip5221** [cloudflare/cloudflared#432] opened 2021-08-05 15:05 UTC
Installation of cloudflared has consistently deleted all my PATH variables on windows.

-> Make sure to backup PATH before installation!

**Comment by sudarshan-reddy** [comment] 2021-08-05 15:58
Hey! Thanks for the report and sorry about that. Just to help me reproduce, can you give me the windows environment you saw the problem on?

**Comment by philip5221** [comment] 2021-08-06 14:12
The Problem occurs when using the cloudflared-windows-amd64.msi installer for windows from version 2021.8.1.

This is my env on one of the machines this happened on - has now happened on 3 different windows systems.
You can see the difference in the length of the PATH variables.

[env_before.txt](https://github.com/cloudflare/cloudflared/files/6946041/env_before.txt)
[env_after.txt](https://github.com/cloudflare/cloudflared/files/6946042/env_after.txt)

To see where this problem comes from look at the following picture:
The system PATH is completely deleted/replaced by cloudflared - therefore being a lot shorter than before.

![Screenshot 2021-08-06 env](https://user-images.githubusercontent.com/34609809/128523152-5bfcb3ec-a49d-487d-97db-c922fa2080d3.png)

**Comment by whalehub** [comment] 2021-08-07 19:57
I can confirm that I'm able to reproduce this issue on my Windows 10 Pro 21H1 machine. This is a pretty serious bug because it breaks dozens of programs that rely on Window's built-in tools being discoverable via the Path variable.

**Comment by sudarshan-reddy** [comment] 2021-08-07 20:12
Yep. I'm on this. I'm temporary removing msi releases from here until the next release. You will still be able to use the `exe`s though.

**Comment by sudarshan-reddy** [comment] 2021-08-09 17:52
The new release fixes this. I tested it on one of my VMs and it seems good. Can one of you guys confirm? Again, thanks so much for reporting this.

**Comment by whalehub** [comment] 2021-08-10 14:09
@sudarshan-reddy I can confirm that the issue is fixed in the new release.

**Closed** 2021-08-10 21:22 UTC
Labels: bug, confirmed, awaiting reply
