### ISSUE TITLE
Cloudflared access not launching a browser window when ran in WSL

### ISSUE THREAD

**Issue by johanwestling** [cloudflare/cloudflared#192] opened 2020-04-20 07:21 UTC
I've integrated the Cloudflared CLI in our localhost setup to be able to send requests to backend services behind Cloudflare. This work very nicely with Mac, Linux and Windows throughout WSL (Windows Subsystem for Linux). 

But there is a difference in the procedure when running on Windows (WSL) as one would have to copy & paste the URL to a browser instead of the browser auto-launching as in other platforms.

It's a minor issue, but I'd also would think it's a minor thing to solve as this is probably due to the fact that the WSL distro don't have a browser installed by default. And in most cases one would like the default browser within the host (Windows) to launch instead of a WSL distro installed browser.

After a bit of research in to this it seems like running `explorer.exe https://url.tld` would be a fairly straight forward way of having the WSL distro launch the default browser in Windows with the provided URL.

Also had a quick look at the access cmd code but didn't notice where the browser launch is happens (go is not too familiar for me).

I'd be happy to make an attempt at a fix or helping someone solve this if there is interest. 🙂

**Comment by daltoniam** [comment] 2020-07-15 20:35
Thanks for the report. We would really appreciate a PR! Right now you can find the windows specific browser open call here: https://github.com/cloudflare/cloudflared/blob/master/cmd/cloudflared/shell/launch_browser_windows.go#L16 (this is the equivalent of running "start https://url.tld" in command prompt. )

Also the access cmd code is calling the browser launch from here: https://github.com/cloudflare/cloudflared/blob/master/cmd/cloudflared/transfer/transfer.go#L42

**Comment by johanwestling** [comment] 2020-07-19 05:36
Thank you for the pointer, I'll have a look and see if I can get something going for a PR during this week 🙂

**Comment by johanwestling** [comment] 2020-07-23 08:08
Okay so I've been able to get the default browser in Windows launch properly when running the `cloudflared access login ...` command. 

Tried out various options but ended up with using `wslview` as it seemed most resilient to check if it exists and only then use that over `xdg-open`. 

**See change here:**
https://github.com/johanwestling/cloudflared/pull/1/files

Although this fixed the opening of the browser it seems like the "dance" to get the access token is not working out. I've looked into this too and notice that it's because I get a timeout when the `poll` function (in cmd/cloudflared/transfer/transfer.go) tries to make the request with `client.Get`.

Getting this kind of message with printing out the `resp` from `client.Get`:
```
https://login.argotunnel.com/transfer/ ...
&{408 Request Timeout 408 HTTP/2.0 2 0 map[Cf-Cache-Status:[DYNAMIC] ...
```

@daltoniam any ideas what this might be related to? Tried to curl the login.argotunnel.com url also but same timeout happened there too.

**Comment by daltoniam** [comment] 2020-07-23 21:24
The poll failing with a timeout is expected behavior. It is waiting for a token (the user to go through the sign in flow). Until that nonce token is update on the backend after the user logs in, the transfer url will poll up to 10 times with a 60 second timeout waiting for token. The curl command will timeout too, because it is acting in the place of waiting for a token (which is never sent because nothing is logging in on that token).

**Comment by johanwestling** [comment] 2020-07-25 08:40
Ah, then it's probably the company network that is my issue, it bypasses the cloudflare access. 

I'll give it a go at home and see if it works as intended in a normal network 🙂

**Comment by TownLake** [comment] 2020-09-06 09:22
@johanwestling we're going to close this out now that a few weeks have passed without hearing back.

**Closed** 2020-09-06 09:21 UTC
Labels: awaiting reply

**Comment by johanwestling** [comment] 2020-09-06 10:48
I understand that. I did manage to get the browser starting properly, but was unable to get the cli to pick up the token. I'm suspecting it's something to do with cli running in WSL while browser running in Windows and them being seen as separate devices.

Might do some more investigation into this at some point, but for now it's fine to close this 🙂
