### ISSUE TITLE
cloudflared release 2023.5.1 crashes when running from the cli with --url

### ISSUE THREAD

**Issue by francispereira** [cloudflare/cloudflared#974] opened 2023-05-24 18:46 UTC
**Describe the bug**
When origin is defined using `--url` and no config file with ingress rules are present , cloudflared crashes when the first request is received

**To Reproduce**
1. Configure: No configuration is required. Simply run the tunnel by setting TUNNEL_TOKEN and TUNNEL_LOGLEVEL
3. Run `./cloudflared-linux-amd64-2023.5.1 tunnel --url http://localhost:80 --no-autoupdate run`
```
panic: runtime error: index out of range [-1]

goroutine 226 [running]:
github.com/cloudflare/cloudflared/ingress.Ingress.FindMatchingRule({{0xc000966640, 0x1, 0x1}, {0x21c4d70, 0x0, 0x0}, {{0x6fc23ac00}, {0x2540be400}, {0x6fc23ac00}, 0x0, ...}}, ...)
	/cfsetup_build/ingress/ingress.go:61 +0x13a
github.com/cloudflare/cloudflared/proxy.(*Proxy).ProxyHTTP(0xc0003a1b80, {0x1439380?, 0xc0004f8ac8}, 0xc0004f8ab0, 0x50?)
	/cfsetup_build/proxy/proxy.go:100 +0x425
github.com/cloudflare/cloudflared/connection.(*QUICConnection).dispatchRequest(0xc000583c00, {0x1433060, 0xc000196240}, 0xc0001ceb50, {0x10?, 0xc00006d800?}, 0xc0008c7860)
	/cfsetup_build/connection/quic.go:272 +0x282
github.com/cloudflare/cloudflared/connection.(*QUICConnection).handleDataStream(0xc000583c00, {0x1433060, 0xc000196240}, 0xc00006d800?)
	/cfsetup_build/connection/quic.go:239 +0x79
github.com/cloudflare/cloudflared/connection.(*QUICConnection).handleStream(0x4?, {0x1433060, 0xc000196240}, {0x1430600?, 0xc0004f8a20})
	/cfsetup_build/connection/quic.go:221 +0x175
github.com/cloudflare/cloudflared/connection.(*QUICConnection).runStream(0xc000583c00, {0x7f9abcd18cc8, 0xc0001de8c0})
	/cfsetup_build/connection/quic.go:201 +0x128
created by github.com/cloudflare/cloudflared/connection.(*QUICConnection).acceptStream
	/cfsetup_build/connection/quic.go:187 +0x88
```

If it's an issue with Cloudflare Tunnel:
6. Tunnel ID : 41ac91ad-0d90-427d-907e-4899aad02a11
7. cloudflared config: No config file is provided

**Full debug logs**

``` 
./cloudflared-linux-amd64-2023.5.1 tunnel --url http://localhost:80 --no-autoupdate run
2023-05-24T18:39:45Z DBG Loading configuration from /usr/local/etc/cloudflared/config.yml
2023-05-24T18:39:45Z INF Starting tunnel tunnelID=41ac91ad-0d90-427d-907e-4899aad02a11
2023-05-24T18:39:45Z INF Version 2023.5.1
2023-05-24T18:39:45Z INF GOOS: linux, GOVersion: go1.19.6, GoArch: amd64
2023-05-24T18:39:45Z INF Settings: map[no-autoupdate:true url:http://localhost:80]
2023-05-24T18:39:45Z INF Environmental variables map[TUNNEL_LOGLEVEL:debug TUNNEL_TOKEN:*****]
2023-05-24T18:39:45Z INF Generated Connector ID: 0a12362e-9cd8-41ae-9909-9557756ef4b9
2023-05-24T18:39:45Z INF cloudflared will not automatically update if installed by a package manager.
2023-05-24T18:39:45Z DBG Fetched protocol: quic
2023-05-24T18:39:45Z INF Initial protocol quic
2023-05-24T18:39:45Z INF ICMP proxy will use 172.31.91.182 as source for IPv4
2023-05-24T18:39:45Z INF ICMP proxy will use fe80::10d7:78ff:fea7:70e3 in zone eth0 as source for IPv6
2023-05-24T18:39:45Z WRN The user running cloudflared process has a GID (group ID) that is not within ping_group_range. You might need to add that user to a group within that range, or instead update the range to encompass a group the user is already in by modifying /proc/sys/net/ipv4/ping_group_range. Otherwise cloudflared will not be able to ping this network error="Group ID 1000 is not between ping group 1 to 0"
2023-05-24T18:39:45Z DBG ICMP proxy feature is disabled error="cannot create ICMPv4 proxy: Group ID 1000 is not between ping group 1 to 0 nor ICMPv6 proxy: socket: permission denied"
2023-05-24T18:39:45Z WRN ICMP proxy feature is disabled error="cannot create ICMPv4 proxy: Group ID 1000 is not between ping group 1 to 0 nor ICMPv6 proxy: socket: permission denied"
2023-05-24T18:39:45Z DBG edge discovery: looking up edge SRV record domain=_v2-origintunneld._tcp.argotunnel.com event=0
2023-05-24T18:39:45Z DBG edge discovery: resolved edge addresses addresses=["198.41.192.7","198.41.192.27","198.41.192.37","198.41.192.47","198.41.192.57","198.41.192.67","198.41.192.77","198.41.192.107","198.41.192.167","198.41.192.227","2606:4700:a0::10","2606:4700:a0::1","2606:4700:a0::2","2606:4700:a0::3","2606:4700:a0::4","2606:4700:a0::5","2606:4700:a0::6","2606:4700:a0::7","2606:4700:a0::8","2606:4700:a0::9"] event=0
2023-05-24T18:39:45Z DBG edge discovery: resolved edge addresses addresses=["198.41.200.113","198.41.200.193","198.41.200.233","198.41.200.13","198.41.200.23","198.41.200.33","198.41.200.43","198.41.200.53","198.41.200.63","198.41.200.73","2606:4700:a8::9","2606:4700:a8::10","2606:4700:a8::1","2606:4700:a8::2","2606:4700:a8::3","2606:4700:a8::4","2606:4700:a8::5","2606:4700:a8::6","2606:4700:a8::7","2606:4700:a8::8"] event=0
2023-05-24T18:39:45Z DBG edge discovery: looking up edge SRV record domain=_v2-origintunneld._tcp.argotunnel.com event=0
2023-05-24T18:39:45Z INF Starting metrics server on 127.0.0.1:38705/metrics
2023-05-24T18:39:45Z DBG edge discovery: resolved edge addresses addresses=["198.41.192.227","198.41.192.7","198.41.192.27","198.41.192.37","198.41.192.47","198.41.192.57","198.41.192.67","198.41.192.77","198.41.192.107","198.41.192.167","2606:4700:a0::9","2606:4700:a0::10","2606:4700:a0::1","2606:4700:a0::2","2606:4700:a0::3","2606:4700:a0::4","2606:4700:a0::5","2606:4700:a0::6","2606:4700:a0::7","2606:4700:a0::8"] event=0
2023-05-24T18:39:45Z DBG edge discovery: resolved edge addresses addresses=["198.41.200.73","198.41.200.113","198.41.200.193","198.41.200.233","198.41.200.13","198.41.200.23","198.41.200.33","198.41.200.43","198.41.200.53","198.41.200.63","2606:4700:a8::8","2606:4700:a8::9","2606:4700:a8::10","2606:4700:a8::1","2606:4700:a8::2","2606:4700:a8::3","2606:4700:a8::4","2606:4700:a8::5","2606:4700:a8::6","2606:4700:a8::7"] event=0
2023-05-24T18:39:45Z DBG edge discovery: giving new address to connection connIndex=0 event=0 ip=198.41.192.27
2023-05-24T18:39:46Z INF Registered tunnel connection connIndex=0 connection=17a97bd6-295c-49dd-8dca-30ee1cb9e504 event=0 ip=198.41.192.27 location=IAD protocol=quic
2023-05-24T18:39:46Z DBG edge discovery: giving new address to connection connIndex=1 event=0 ip=198.41.200.53
2023-05-24T18:39:46Z INF Registered tunnel connection connIndex=1 connection=7e9c5bf9-b0dc-4901-8c86-25e63dca7a11 event=0 ip=198.41.200.53 location=MIA protocol=quic
2023-05-24T18:39:47Z INF Updated to new configuration config=null version=0
2023-05-24T18:39:47Z DBG edge discovery: giving new address to connection connIndex=2 event=0 ip=198.41.192.37
2023-05-24T18:39:47Z INF Registered tunnel connection connIndex=2 connection=5a810c9e-d760-458d-b884-dc6ed813c9f6 event=0 ip=198.41.192.37 location=IAD protocol=quic
2023-05-24T18:39:48Z DBG edge discovery: giving new address to connection connIndex=3 event=0 ip=198.41.200.63
2023-05-24T18:39:48Z INF Registered tunnel connection connIndex=3 connection=c02463e6-47d3-4d3b-abfd-1fee7056a6a8 event=0 ip=198.41.200.63 location=MIA protocol=quic


panic: runtime error: index out of range [-1]

goroutine 226 [running]:
github.com/cloudflare/cloudflared/ingress.Ingress.FindMatchingRule({{0xc000966640, 0x1, 0x1}, {0x21c4d70, 0x0, 0x0}, {{0x6fc23ac00}, {0x2540be400}, {0x6fc23ac00}, 0x0, ...}}, ...)
	/cfsetup_build/ingress/ingress.go:61 +0x13a
github.com/cloudflare/cloudflared/proxy.(*Proxy).ProxyHTTP(0xc0003a1b80, {0x1439380?, 0xc0004f8ac8}, 0xc0004f8ab0, 0x50?)
	/cfsetup_build/proxy/proxy.go:100 +0x425
github.com/cloudflare/cloudflared/connection.(*QUICConnection).dispatchRequest(0xc000583c00, {0x1433060, 0xc000196240}, 0xc0001ceb50, {0x10?, 0xc00006d800?}, 0xc0008c7860)
	/cfsetup_build/connection/quic.go:272 +0x282
github.com/cloudflare/cloudflared/connection.(*QUICConnection).handleDataStream(0xc000583c00, {0x1433060, 0xc000196240}, 0xc00006d800?)
	/cfsetup_build/connection/quic.go:239 +0x79
github.com/cloudflare/cloudflared/connection.(*QUICConnection).handleStream(0x4?, {0x1433060, 0xc000196240}, {0x1430600?, 0xc0004f8a20})
	/cfsetup_build/connection/quic.go:221 +0x175
github.com/cloudflare/cloudflared/connection.(*QUICConnection).runStream(0xc000583c00, {0x7f9abcd18cc8, 0xc0001de8c0})
	/cfsetup_build/connection/quic.go:201 +0x128
created by github.com/cloudflare/cloudflared/connection.(*QUICConnection).acceptStream
	/cfsetup_build/connection/quic.go:187 +0x88
```

**Expected behavior**
Cloudflared does not crash

**Environment and versions**
 - OS: Amazon Linux 2
 - Architecture: x86_6
 - Version:

**Comment by marcosvrs** [comment] 2023-05-25 21:21
Same here.

**Comment by ppmathis** [comment] 2023-06-04 14:07
I was facing the exact same crash with `2023.5.1`, but was able to pinpoint the specific problem that caused this issue. I followed these steps on my first attempt, with the idea that I would have a new CF tunnel with locally managed configuration:

- Create a new Cloudflare Tunnel via the Zero Trust UI
- Make absolutely no configuration attempt in the Zero Trust UI, simply let it be as-is
- Create a local configuration and credentials file on the target host, using the secret retrieved from the token (base64 decode and use the value of `s` - this is more convoluted than necessary, but I wanted to manage it via Ansible, however as far as I understand using `--token` will result in the same outcome)
- Ensure the local configuration file contains a proper ingress catch-all rule
- Run `cloudflared` as a service using said configuration and credentials file

For the sake of completeness, these are the files I've used:

```yaml
credentials-file: /etc/cloudflared/creds.json
ingress:
  - service: http_status:404
tunnel: xxx
```

```json
{
  "AccountTag": "xxx",
  "TunnelID": "xxx",
  "TunnelName": "xxx",
  "TunnelSecret": "xxx"
}
```

Just like the OP, the `cloudflared` process properly started up, but as soon as a first request was handled the process immediately crashed at `ingress.Ingress.FindMatchingRule`. I noticed something odd in the logs though:

```
2023-05-24T18:39:47Z INF Updated to new configuration config=null version=0
```

This seemed weird to me, as a configuration of `null` does not sound sane. I then read some more about how Cloudflare Tunnel works and learned that tunnels created via the Zero Trust UI are always remote-managed. It now somehow seems that a newly created tunnel via said Zero Trust UI contains an empty remote configuration, possibly `null`. As soon as `cloudflared` connects to the edge servers, the remote configuration `null` is being applied, overwriting the local configuration completely, therefor causing `ingress` to be an empty array, meaning that there is no longer any catch-all rule available, causing the lookup of index `-1` (last array element) to fail.

If remote configuration is desired instead, I confirmed that simply creating some public hostname mapping in the Zero Trust UI fixed the issue and results in a new log message similar to the above one, with `config` containing an actual dictionary of ingress rules instead of `null`.

As I however do not want to use remote configuration in the first place and strongly agree with #843, I managed to get things working by creating a Cloudflare tunnel via the API, as [described in the forums](https://community.cloudflare.com/t/creating-an-argo-tunnel-programmatically/228501). This created a new tunnel which is locally configured and requests were now properly handled based on the local configuration, with the above log message disappearing completely as well.

I did not really have time for debugging the specific issue, but based on a comparison between `2023.4.2` and `2023.5.1` maybe https://github.com/cloudflare/cloudflared/commit/ff9621bbd521dd76c0464481755f86b7e4518b67 could be the culprit? Just a wild guess though.

**Comment by obezuk** [comment] 2023-06-07 16:09
Thanks for this context @ppmathis, we're tracking this internally. Tunnel's created via the dashboard are intended to be managed via a config file pushed via the [API](https://developers.cloudflare.com/api/operations/cloudflare-tunnel-configuration-put-configuration).

If you would like to use local config files, I recommend creating your Tunnel via CLI, or [API](https://developers.cloudflare.com/api/operations/cloudflare-tunnel-create-a-cloudflare-tunnel) with config_src set to local.

**Comment by jcsf** [comment] 2023-06-15 09:11
Hi @francispereira, @ppmathis, @marcosvrs and @wmorrell. Thank you for reporting this. A fix has been made in the commit [925ec1](https://github.com/cloudflare/cloudflared/commit/925ec100d691662d129723072c0c3a7cae1862bb), and will be released on the next version. It will ensure that cloudflared no longer crashes in this situation. Despite that, as already explained by @obezuk, if you would like to use local configuration you should create the tunnel via CLI or the API with the config_src set to local, otherwise the remote configuration will **always** override your local one.

**Comment by jcsf** [comment] 2023-06-15 15:29
Released version with the fix: https://github.com/cloudflare/cloudflared/releases/tag/2023.6.0

**Comment by marcosvrs** [comment] 2023-06-15 16:26
Hi @jcsf,
So, this will be outdated, or?
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/trycloudflare/

**Closed** 2023-06-16 20:52 UTC
Labels: Type: Bug, Confirmed, Priority: Normal
