### ISSUE TITLE
Can you add support for s390x architecture

### ISSUE THREAD

**Issue by misakano7545** [cloudflare/cloudflared#612] opened 2022-04-06 09:37 UTC
IBM has their own architecture called s390x, but your project doesnt have its files. Do you have plan for support it?

**Comment by nmldiegues** [comment] 2022-04-06 09:39
I believe this is a duplicate of https://github.com/cloudflare/cloudflared/issues/567 
Let's track it there

**Closed by nmldiegues** 2022-04-06 09:39 UTC
Labels: awaiting reply, feature-request
