### ISSUE TITLE
panic: runtime error for long lived request

### ISSUE THREAD

**Issue by ssalinas** [cloudflare/cloudflared#141] opened 2019-10-08 18:55 UTC
👋 we are testing argo tunnel for eventual use with production level traffic. While playing around with a load testing service we found we could repeatedly crash cloudflared with a specific request.

Context:

- argo tunnel is running as a sidecar process to nginx in kubernetes (not the ingress controller, just a container running cloudflared). Nginx then proxies to a java dropwizard service as its upstream
- In cloudflare this is set up as:
  - pool: ngx-argo-loadtest
  - load balancer: ngx-argo-loadtest.(domain1).net
  - load test code is hitting loadtest.(domain2).com which is a CNAME to ngx-argo-loadtest.(domain1).net . Healthchecks pass for this setup and simple requests to other endpoints can be made with no issue
- The load test hits an endpoint on loadtest.(domain2).com which proxies to the dropwizard service that then returns a random bunch of bytes of varying size

Result:

A curl to this endpoint actually succeeds:
```
*   Trying 104.17.247.168...
* TCP_NODELAY set
* Connected to loadtest.hubapiqa.com (104.17.247.168) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=ssl826607.cloudflaressl.com
*  start date: Sep 11 00:00:00 2019 GMT
*  expire date: Mar 19 23:59:59 2020 GMT
*  subjectAltName: host "(domain2)" matched cert's "*.(domain2)"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f8b28002400)
> GET /nginx/load-test HTTP/2
> Host: (domain2)
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< date: Tue, 08 Oct 2019 18:51:32 GMT
< content-type: text/plain; charset=utf-8
< content-length: 33
< set-cookie: __cfduid=dd4f8e3cd37e877ebb39726f1feb800dd1570560692; expires=Wed, 07-Oct-20 18:51:32 GMT; path=/; domain=(domain2); HttpOnly; Secure
< access-control-allow-credentials: false
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 522a4e856e812208-EWR
<
* Connection #0 to host loadtest.hubapiqa.com left intact
!΀�*�0���=0���
```

However, any subsequent requests fail with a 530 code until the cloudflared container restarts. It logs this exception on exit:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7fb1ba]

goroutine 32277 [running]:
github.com/cloudflare/cloudflared/h2mux.(*h2DictWriter).Close(0xc0001dac80, 0x14791a0, 0xc0001dac80)
	/cfsetup_build/src/github.com/cloudflare/cloudflared/h2mux/h2_dictionaries.go:545 +0x2a
github.com/cloudflare/cloudflared/h2mux.(*MuxedStream).CloseWrite(0xc0002245a0, 0x0, 0x0)
	/cfsetup_build/src/github.com/cloudflare/cloudflared/h2mux/muxedstream.go:189 +0xf2
github.com/cloudflare/cloudflared/h2mux.(*MuxedStream).Close(0xc0002245a0, 0xc00030e374, 0xc0005c9b18)
	/cfsetup_build/src/github.com/cloudflare/cloudflared/h2mux/muxedstream.go:166 +0x2f
github.com/cloudflare/cloudflared/h2mux.(*MuxReader).handleStream(0xc00059dd60, 0xc0002245a0)
	/cfsetup_build/src/github.com/cloudflare/cloudflared/h2mux/muxreader.go:263 +0x65
created by github.com/cloudflare/cloudflared/h2mux.(*MuxReader).receiveHeaderData
	/cfsetup_build/src/github.com/cloudflare/cloudflared/h2mux/muxreader.go:253 +0x538
```

**Comment by pims** [comment] 2019-11-26 04:26
@ssalinas I haven't been able to reproduce the bug you’ve ran into, but here's a fix for the nil pointer you're seeing: https://github.com/cloudflare/cloudflared/pull/154

**Comment by daltoniam** [comment] 2020-07-15 20:47
Since the PR resolved the crash I'm going to close this issue. If we need further investigation we can reopen it or open a new issue. Thanks!

**Closed by daltoniam** 2020-07-15 20:47 UTC
